// ============================================================================
//  DEPTH - living creature AI for the parkour levels (ParkourReference1.2.pdf, "Advanced Beast AI").
//
//  Every beast runs the reference's four-tier pipeline each tick:
//    1. senses    - a sight cone with a real line-of-sight raycast through the tiles, hearing that falls off
//                   with distance (I / (1 + k d^2)), and smell read off a diffusing scent grid (blood, the
//                   diver's trail); what it notices goes into a short decaying memory, so a predator keeps
//                   hunting where it last saw you after you break line of sight
//    2. drives    - hunger, fear, fatigue, carried between ticks
//    3. utility   - sigmoid response curves score Hunt / Flee / Scavenge / Rest / Investigate / Explore /
//                   Wander (plus species extras); the best wins, with hysteresis so it doesn't dither
//    4. motor     - an A* route across the level (walkers on floor spans with steps, drops and hops;
//                   swimmers and fliers through open water/air), then physics: acceleration, drag, gravity
//                   for walkers, tile collision
//  Personalities: aggression, bravery, energy, curiosity, plus intelligence (a dim beast forgets fast, never
//  leads its target and steers greedily) and wanderlust (roams far from its den and migrates). About 15%
//  roll one of the reference's 12 abnormal profiles, which override the utility choice.
//  Dens are generated by the level (tile 'D'): prey flee to them, beasts rest in them, and the population
//  comes back out of them after something dies.
//
//  This file holds the engine; each biome supplies a species table and a food web (see beasts.cpp).
// ============================================================================
#pragma once
#include "raylib.h"
#include <cstdint>
#include <vector>

struct PlatformState;

enum class Abnormal : uint8_t {
    None, RabidEnraged, Kleptomaniac, HyperProtectiveParent, SuicidalSelfDestructive, ParasiticHost, CovetousHoarder,
    SymbioticCompanion, TerritorialTyrant, PyromaniacShockSeeker, GluttonousDevourer, PhobicNyctophobic, MalignantAlpha, COUNT
};
const char* AbnormalName(Abnormal a);

struct PersonalityProfile {
    float aggression = 0.5f; // 0 = pacifist/flees a fight, 1 = relentless hunter
    float bravery = 0.5f;    // 0 = flees anything bigger than itself, 1 = attacks larger predators
    float energy = 0.5f;     // 0 = lethargic, 1 = hyperactive
    float curiosity = 0.5f;  // 0 = ignores disturbances, 1 = investigates every sound
    float intelligence = 0.5f; // 0 = dim (forgets fast, no prediction, greedy steering), 1 = sharp
    float wanderlust = 0.5f;   // 0 = never strays from its den, 1 = explores the whole level and migrates
    Abnormal abnormal = Abnormal::None;
};

enum class MoveMode : uint8_t { Walk, Swim, Fly, Sessile };
enum class BeastAct : uint8_t {
    Idle, Wander, Explore, Hunt, Stalk, Coil, Strike, Eat, Scavenge, Flee, Hide, Rest, Investigate,
    Ambush, Mob, Groom, Guard, Follow, Latched, Drift, Puffed
};
const char* BeastActName(BeastAct a);
enum class BeastLife : uint8_t { Alive, Corpse, Gone };

constexpr int BEAST_DIVER = -2; // a target/source index meaning the diver
constexpr int BEAST_MEM = 12;
enum MemKind : uint8_t { MEM_THREAT, MEM_PREY, MEM_SOUND, MEM_FOOD };
struct BeastMemory { Vector2 pos{0, 0}, vel{0, 0}; float strength = 0, t = -1e9f; uint8_t kind = 0; int source = -1, sid = 0; };

constexpr int SPINE = 8;
struct Beast {
    int species = 0, id = 0;
    Vector2 pos{0, 0}, vel{0, 0};
    int den = -1;
    PersonalityProfile pers;
    BeastAct act = BeastAct::Idle;
    BeastLife life = BeastLife::Alive;
    float actT = 0, thinkT = 0;
    float hunger = 0.3f, fear = 0, fatigue = 0, health = 1;
    float facing = 1, phase = 0, scale = 1, mass = 1;
    int target = -1, targetId = 0; // beast index (checked against its id) or BEAST_DIVER
    float alarmT = 0, stuckT = 0, shoveT = 0;
    Vector2 lastPos{0, 0};
    Vector2 goal{0, 0};
    std::vector<Vector2> path;
    int pathI = 0;
    float replanT = 0;
    Vector2 pathGoal{-1e9f, -1e9f};
    BeastMemory mem[BEAST_MEM];
    uint32_t trauma = 0;          // species bits (bit 31 = the diver) that once badly hurt it: permanent extra fear
    int school = -1;              // schooling fish / packs
    bool straggler = false;       // won't keep formation under threat - the one a predator picks off
    bool hidden = false, grounded = false;
    float corpseT = 0, meat = 1;  // corpse: time dead, and how much is left to eat
    float special = 0, special2 = 0, cooldown = 0;
    int latched = -1;             // parasites riding a host
    int carry = -1;               // hoarders dragging a corpse
    Vector2 territory{0, 0};
    Vector2 spine[SPINE];         // segmented bodies follow the head (serpentine / tail animation)
};

struct SpeciesDef {
    const char* name;
    MoveMode move;
    float mass;        // relative body mass (the diver is 70)
    float radius;      // px
    float speed, sprint, accel;
    float sight, fov;  // px, half-angle in radians (PI = all round)
    float hearing, smell;
    float hungerRate;  // per second
    float diverFear;   // how much the diver frightens it
    float diverPrey;   // how much it wants to hunt the diver (0 = never)
    bool lethal;       // touching it can kill the diver (see BeastLethalNow)
    bool social;       // schools / packs
    int band;          // swimmers: preferred height above the floor, in tiles
    int population;    // head count the dens keep topping up
    float denAffinity; // how much it uses dens to rest and hide
    float scavenge;    // appetite for corpses (0 = never)
};
struct FoodEdge { int pred, prey; float pref; };

struct Den { int tx = 0, ty = 0; Vector2 pos{0, 0}; float repopT = 0; };
struct SoundEvent { Vector2 pos{0, 0}; float intensity = 0, life = 0; int source = -1; };
struct InkPuff { Vector2 pos{0, 0}; float life = 0, r = 60; };

// A downsampled scalar field that spreads (diffusion), fades (decay) and drifts (a constant current). Solid
// tiles don't carry scent. Beasts read its gradient to follow a trail uphill toward its source.
struct ScentGrid {
    int w = 0, h = 0;
    float cell = 32, diffusion = 6.0f, decay = 0.06f;
    Vector2 drift{0, 0};
    std::vector<float> blood, trail, tmp;
    void Init(int cw, int chh, float cellPx);
    void Emit(std::vector<float>& ch, Vector2 at, float amount);
    void Step(float dt, const std::vector<uint8_t>& solidCells);
    float Sample(const std::vector<float>& ch, Vector2 at) const;
    Vector2 Gradient(const std::vector<float>& ch, Vector2 at) const;
};

// The level as the creatures see it: which tiles are solid, which are dangerous, and A* over them.
struct NavGrid {
    int w = 0, h = 0;
    float tile = 32;
    std::vector<uint8_t> solid, hazard;
    mutable std::vector<float> g;
    mutable std::vector<int> parent;
    mutable std::vector<uint32_t> stamp;
    mutable uint32_t curStamp = 0;
    bool Solid(int x, int y) const { return x < 0 || x >= w || (y >= 0 && y < h && solid[y * w + x]); }
    bool Open(int x, int y) const { return x >= 0 && x < w && y >= 0 && y < h && !solid[y * w + x]; }
    bool Standable(int x, int y) const { return Open(x, y) && Solid(x, y + 1); }
    bool Hazard(int x, int y) const { return x >= 0 && x < w && y >= 0 && y < h && hazard[y * w + x]; }
    bool LineOfSight(Vector2 a, Vector2 b) const;
    int FloorBelow(int x, int y) const; // the first solid row at or below y (h if none)
    bool FindPath(MoveMode m, Vector2 from, Vector2 to, std::vector<Vector2>& out, int maxExpand) const;
};

struct BeastWorld {
    int biome = -1;
    bool active = false;
    std::vector<Beast> beasts;
    std::vector<Den> dens;
    std::vector<SoundEvent> sounds;
    std::vector<InkPuff> ink;
    ScentGrid scent;
    NavGrid nav;
    float time = 0, scentT = 0, repopT = 0, noiseT = 0;
    float limitX = 1e9f;          // creatures stay out of a boss arena appended past this x
    int nextId = 1, replansLeft = 0;
    unsigned seed = 1, rng = 1;
    int kills = 0, scavenged = 0, births = 0, hides = 0, abnormals = 0; // running tallies, read by --verify-beasts
};

// The host (platformer.cpp) calls these.
bool BeastsUsed(int level);                               // does this level run the living-AI system yet?
void BeastsBuild(PlatformState& p, unsigned seed);         // nav, scent, dens, spawns (after the tiles exist)
void BeastsUpdate(PlatformState& p, float dt);
void BeastsNoise(PlatformState& p, Vector2 at, float intensity); // the diver's footfalls, landings, gunfire, blasts
void BeastsDiverRespawned(PlatformState& p, Vector2 at);          // lethal beasts near a checkpoint scatter instead of camping it
bool BeastLethalNow(const PlatformState& p, const Beast& b);     // is touching this beast fatal right now?
bool BeastsTouchDiver(const PlatformState& p, Rectangle diver);  // any lethal contact this frame
const SpeciesDef& BeastSpecies(int biome, int species);
int BeastSpeciesCount(int biome);
bool VerifyBeasts();                                       // depth.exe --verify-beasts

// Hull species indices (biome = PL_HULL).
enum HullSpecies { HS_SPRAT, HS_SHRIMP, HS_OCTOPUS, HS_PUFFER, HS_LEECH, HS_ANEMONE, HS_HERMIT, HS_BRITTLE, HS_CRAB, HS_EEL, HS_COUNT };
