MAP="Atlantis, the Forgotten City"; SLUG="atlantis"; FILE="RedTide_Atlantis_data.xlsx"
README_EXTRA=["Atlantis-specific: DISTRICTS and BUILDING TYPES tables in Blockout drive the city generator (districts are rings and sectors on the hill; each building type has a footprint, a count, and the species it hosts).",
"AQUEDUCT and CISTERN GRATES tables list the blood-flow network and the Wyrm's exits. Depth = metres below the surface at the summit (the city floor is 30 m at the top, 90 m at the wall)."]
S=[
("Sardine","Fish",1,1,"schooler","Schooler","school",60,"Lower Town","","",0,0.0,0.9,0.2,15,8,20,0,"none",0,[],"Street schools; the city's blood battery",1),
("Cardinalfish","Fish",1,1,"nocturnal","Grazer","group",10,"Lower Town","Bathhouse sponges","",0,0.0,0.8,0.2,10,6,10,0,"none",0,[],"Cellars and sponges",1),
("Cleaner Goby","Fish",1,0,"cleaner","Grazer","group",4,"Bathhouses","","",0,0.0,0.6,0.5,8,6,8,0,"none",0,[],"Cleaning stations at the bath drains; hosts calm within 6 m",0),
("Snapping Shrimp","Crustacean",1,2,"swarm,sessile","Swarmer","swarm",100,"Lower Town","","",0,0.0,1.0,0.0,2,2,4,0,"none",0,[],"Wall colonies; constant 1-noise crackle that masks gunfire by 15% in the Lower Town",0),
("Porcelain Crab","Crustacean",1,1,"","Grazer","group",6,"Lower Town","Amphora anemones","",0,0.0,0.8,0.3,4,4,4,0,"underside",1,[],"In anemones; free scrip",2),
("Nudibranch","Mollusc",1,1,"toxic","Grazer","solo",1,"Bathhouses","Bathhouse sponges","",0,0.0,0.3,0.1,2,4,2,0,"none",0,[("Skin",8,0,0,0.5,"","Touch: poison 4 s")],"Bright; poison on touch",2),
("Sea Cucumber","Echinoderm",1,0,"scavenger","Grazer","group",8,"Lower Town","","",5,0.0,0.2,0.1,0,15,0,0,"none",0,[("Threads",0,0.3,10.0,1,"Contracts","Sticky threads: slow 30% for 4 s")],"Cleans corpses at 0.4 blood/s",2),
("Feather Star","Echinoderm",1,1,"sessile","Grazer","group",6,"Forum","Column coral","",0,0.0,0.0,0.0,0,0,0,0,"none",0,[],"On the columns; harmless",1),
("Long-spined Urchin","Echinoderm",1,1,"","Grazer","group",15,"Lower Town","","",0,0.0,0.1,0.0,0,3,0,0,"none",1,[("Spines",10,0,0,0.6,"","Contact 10; bleed 2 s")],"Carpets the stairs",2),
("Bream","Fish",2,1,"schooler","Schooler","school",15,"Farms","Sea lettuce terraces","",0,0.0,0.8,0.2,12,6,12,0,"gills",0,[],"Granary schools",2),
("Salema","Fish",2,1,"schooler","Schooler","school",20,"Farms","Posidonia meadows","",0,0.0,0.9,0.2,12,6,12,0,"gills",0,[],"Farm herds; erratic after grazing the hallucinogenic patch (marks the off-limits meadow)",2),
("Scorpionfish","Fish",2,2,"venom,camouflage","Ambusher","solo",1,"Lower Town","","",0,0.1,0.1,0.1,5,5,5,0,"belly",2,[("Spines",30,0,0,0.6,"","Contact: poison 8 s")],"Invisible on marble until touched",4),
("Cuttlefish","Cephalopod",2,2,"camouflage","Ambusher","solo",1,"Lower Town","","",10,0.3,0.6,0.5,12,8,8,0,"mantle",0,[("Dazzle",0,0.5,6.0,4,"Skin ripples","Aim sway +30% for 3 s")],"Market square",4),
("Slipper Lobster","Crustacean",2,2,"nocturnal","Grazer","group",3,"Lower Town","","",5,0.1,0.7,0.3,6,8,6,0,"underside",2,[],"Under the market stalls",3),
("Mantis Shrimp","Crustacean",2,2,"burrower","Ambusher","solo",1,"Lower Town","","",10,0.5,0.4,0.3,8,8,8,0,"eyes",2,[("Punch",30,0.4,2.0,1.5,"Antennae flick","Breaks a Shell Shield in 2 hits")],"Nests in the toolsmiths' anvils",4),
("Aqueduct Newt","Amphibian",1,2,"amphibious","Grazer","group",8,"Aqueduct","","",0,0.0,0.8,0.3,6,4,6,0,"none",0,[],"Rides the aqueduct channels; harmless",2),
("Cistern Frog","Amphibian",2,2,"amphibious","Grazer","group",6,"Cisterns","","",5,0.1,0.7,0.4,6,6,10,0,"none",0,[],"Croaks echo through the drains: a 2-noise carrier that spreads alarm between districts",3),
("Temple Krait","Reptile",2,2,"venom,air-breather","Patroller","solo",1,"Chapel","","",15,0.5,0.4,0.5,10,10,8,0,"head",0,[("Bite",10,0.5,2.0,1,"Coils","Poison 30 over 10 s")],"Crypt sea snake; surfaces at the caldarium dome",5),
("Water Monitor","Reptile",3,3,"amphibious","Patroller","solo",1,"Bathhouses","",5,30,0.6,0.3,0.4,12,15,12,0,"throat",2,[("Bite",40,0.5,2.0,1.5,"Tongue flicks","Hold 2 s"),("Tail",30,0.4,3.0,2.5,"Turns side-on","Knockback 3 m")],"Prowls the hypocaust rooms and the drill yard; eats ichor-fed crabs",6),
("Cormorant","Bird",2,2,"flying,air-breather","Schooler","school",10,"Courtyards","Courtyard sargassum","",0,0.0,0.9,0.3,25,0,20,0,"none",0,[],"Dives from the courtyard air pockets; a startled flock is a 6-noise alarm",2),
("Moon Jelly Bloom","Cnidarian",2,1,"swarm","Swarmer","swarm",40,"Forum","","",0,0.0,0.0,0.0,0,0,0,0,"none",0,[("Sting",4,0,1.0,1,"","Contact 4/s")],"Drifts the forum",0),
("Man o' War","Cnidarian",2,2,"venom","Swarmer","group",3,"Courtyards","Courtyard sargassum","",0,0.0,0.0,0.0,0,0,0,0,"float",0,[("Tentacles",30,0,1.0,10,"Blue float at the surface","Paralysis 1 s")],"10 m tentacles under the sargassum",2),
("Octopus","Cephalopod",3,3,"thief","Ambusher","solo",1,"Lower Town","Amphora anemones","",30,0.4,0.6,0.9,10,15,8,0,"mantle",0,[("Grab",20,0.5,3.0,2.5,"Arm extends","Steals a held part; flees to its amphora")],"One per amphora street; the toolsmiths' parts are usually in its den",8),
("Conger Eel","Fish",3,3,"","Ambusher","solo",1,"Cisterns","",2,30,0.7,0.2,0.3,8,25,12,0,"gills",1,[("Strike",40,0.4,1.5,2,"A shadow under the grate","Bleed 3 s"),("Drag",25,0.6,5.0,1.5,"Grate rattles","Pulls a diver against the grate 2 s")],"Strikes from any drain grate; retreats into the cistern",6),
("Spider Crab","Crustacean",3,2,"armored,camouflage","Grazer","solo",1,"Farms","Doorway kelp curtains","",0,0.1,0.4,0.2,6,8,6,0,"underside",4,[("Pinch",25,0.5,3.0,1.5,"Only if shot","")],"Decorated with kelp; looks like a bush until it moves",4),
("Sea Bass","Fish",3,3,"","Patroller","solo",1,"Bathhouses","","",30,0.6,0.3,0.4,15,20,12,0,"gills",1,[("Bite",35,0.4,1.5,1.5,"Gill flare","")],"Bathhouse patroller",6),
("Dentex","Fish",3,3,"pair","Pack hunter","pair",2,"Lower Town","","",30,0.7,0.3,0.5,25,20,20,0,"gills",0,[("Slash",35,0.3,1.2,2,"Straightens","Bleed 3 s")],"A fast street hunter in pairs",6),
("Amberjack","Fish",3,3,"pack","Pack hunter","pack",6,"Barracks","","",30,0.7,0.3,0.4,25,20,20,0,"gills",0,[("Ram",25,0.4,1.5,3,"Pack fans out","Knockback 2 m")],"Drills the barracks yard in formation",6),
("Barracuda","Fish",3,3,"","Patroller","solo",1,"Harbor Gate","","",30,0.6,0.3,0.7,25,20,20,0,"gills",0,[("Slash",30,0.3,1.2,2,"Straightens","Bleed 3 s"),("Hit-and-run",45,0.5,4.0,10,"Circles wide","")],"Waits in the gate arch; drawn to flashes",6),
("Lamprey","Fish",2,0,"parasite","Parasite","solo",1,"Cisterns","","",10,0.4,0.4,0.6,10,15,8,0,"none",0,[("Latch",2,0.5,0,0.5,"Circles","Host bleeds 2/s")],"Cistern parasite",2),
("Bluefin Tuna","Fish",4,3,"fast","Patroller","school",3,"Forum","","",0,0.5,0.4,0.3,30,15,20,0,"gills",1,[("Ram",60,0.3,3.0,12,"A silver flash across the plaza","Knockback 4 m")],"Crosses the summit plaza at full speed every 40 s",6),
("Swordfish","Fish",4,3,"fast","Patroller","solo",1,"Forum","","",30,0.7,0.2,0.4,30,20,20,0,"gills",1,[("Charge",100,0.5,4.0,12,"Bill lowers","Impales and pins 2 s")],"Plaza lane",8),
("Loggerhead","Reptile",4,3,"armored,air-breather","Grazer","solo",1,"Courtyards","Courtyard sargassum","",0,0.2,0.4,0.3,12,12,10,0,"neck",4,[("Crush",60,0.8,4.0,1.2,"Head draws back","Destroys a Shell Shield")],"Eats the man o' war under the sargassum",6),
("Monk Seal","Mammal",4,3,"thief,air-breather","Patroller","solo",1,"Courtyards","","",30,0.3,0.5,0.9,15,10,15,0,"none",1,[("Snatch",10,0.5,4.0,2,"Rolls","Steals a held item"),("Bite",50,0.5,2.5,1.5,"Only if shot","")],"Curious thief",6),
("Sandbar Shark","Fish",4,4,"","Patroller","solo",1,"Lower Town","","",70,0.8,0.2,0.5,20,45,20,6,"gills",1,[("Bite",70,0.4,1.8,2,"Pectorals drop","Bleed 4 s"),("Ram",50,0.5,3.0,6,"Straight charge","Knockback 4 m, stun 1 s")],"Patrols the lower town streets; threshold 70; avoids ichor for 60 s",8),
("Leatherback","Reptile",5,1,"air-breather","Grazer","solo",1,"Forum","","",0,0.0,0.4,0.3,12,10,10,0,"neck",3,[("Flipper (if shot)",80,0.8,5.0,3,"Turns","Knockback 6 m")],"Gentle; 100 blood; eats every jelly in the forum if left alone",6),
("Nile Crocodile of the Canals","Reptile",5,4,"amphibious,armored","Territorial","solo",1,"Farms","",10,100,0.8,0.1,0.3,15,35,20,0,"throat",4,[("Death Roll",120,0.9,6.0,2.5,"Rises at a sluice gate","Holds and rolls; teammates have 4 s"),("Snap",60,0.4,2.0,2,"Jaw clicks","Bleed 3 s"),("Tail",45,0.5,3.0,3,"Turns side-on","Knockback 4 m")],"Every canal is its lane; hauls out on the terraces; eats Lost Ones",10),
("Great White","Fish",5,4,"","Wanderer","solo",1,"Beyond the wall","","",150,0.9,0.0,0.7,30,80,30,8,"gills",1,[("Bite",110,0.5,2.0,2.5,"Rolls to one side","Bleed 5 s"),("Ram",70,0.5,4.0,8,"Straight charge","Knockback 5 m, stun 1 s"),("Drag",50,0.7,8.0,2,"Grabs and swims","Carries 10 m; teammates shoot it off")],"Comes over the wall for blood over 150; avoids ichor-scented streets",10),
("Giant Squid","Cephalopod",5,4,"","Ambusher","solo",1,"Library","",10,100,0.9,0.0,0.3,15,30,15,0,"eye",1,[("Tentacle grab",60,0.7,4.0,8,"An arm slides through the doorway","Hold 3 s; drags toward the stacks"),("Beak",120,0.6,5.0,2,"Eye glows in the moss-light","Bleed 5 s")],"Confined to the library stacks; reaches through doorways",10),
("The Cistern Wyrm","Fish",6,5,"boss","Boss","solo",1,"Cisterns","",0,400,1.0,0.0,0.2,15,60,25,10,"gills (when surfaced)",3,[("Surface strike",130,1.0,6.0,4,"The grate rattles, then bursts","Bleed 5 s; destroys the grate"),("Drag below",0,0.8,12.0,3,"Jaws open under a diver","Pulls a diver into the drains; teammates have 6 s to deal 200 to the gills"),("Coil",90,0.6,5.0,5,"Body loops a street","Knockback 6 m; blocks the street 4 s"),("Flood",40,1.2,15.0,15,"Water surges from every grate in the district","Slow 30% for 6 s in the district; blood in the district doubles")],"A conger the length of a street; see Boss",100),
]
D={
"Sardine":{"Plankton":1.0},"Cardinalfish":{"Plankton":0.8,"Snapping Shrimp":0.2},"Cleaner Goby":{"Parasites":1.0},"Snapping Shrimp":{"Detritus":0.7,"Plankton":0.3},"Porcelain Crab":{"Plankton":1.0},
"Nudibranch":{"Bathhouse sponges":0.6,"Detritus":0.4},"Sea Cucumber":{"Corpse":0.5,"Detritus":0.5},"Feather Star":{"Plankton":1.0},"Long-spined Urchin":{"Turf on marble":1.0},
"Bream":{"Sea lettuce terraces":0.6,"Snapping Shrimp":0.4},"Salema":{"Posidonia meadows":1.0},"Scorpionfish":{"Cardinalfish":0.6,"Porcelain Crab":0.4},"Cuttlefish":{"Porcelain Crab":0.5,"Slipper Lobster":0.5},
"Slipper Lobster":{"Long-spined Urchin":0.4,"Detritus":0.6},"Mantis Shrimp":{"Porcelain Crab":0.6,"Slipper Lobster":0.4},"Aqueduct Newt":{"Snapping Shrimp":0.5,"Detritus":0.5},"Cistern Frog":{"Aqueduct Newt":0.5,"Snapping Shrimp":0.5},
"Temple Krait":{"Cardinalfish":0.5,"Aqueduct Newt":0.5},"Water Monitor":{"Porcelain Crab":0.2,"Cistern Frog":0.3,"Long-spined Urchin":0.2,"Ichor-fed crabs":0.3},"Cormorant":{"Sardine":0.7,"Bream":0.3},
"Moon Jelly Bloom":{"Plankton":1.0},"Man o' War":{"Sardine":0.6,"Plankton":0.4},"Octopus":{"Slipper Lobster":0.4,"Mantis Shrimp":0.3,"Porcelain Crab":0.3},"Conger Eel":{"Octopus":0.4,"Cistern Frog":0.3,"Cardinalfish":0.3},
"Spider Crab":{"Sea Cucumber":0.5,"Turf on marble":0.5},"Sea Bass":{"Bream":0.4,"Cuttlefish":0.3,"Temple Krait":0.3},"Dentex":{"Sardine":0.5,"Bream":0.3,"Octopus":0.2},"Amberjack":{"Sardine":0.6,"Salema":0.4},
"Barracuda":{"Sardine":0.7,"Cormorant":0.3},"Lamprey":{"Sea Bass":0.4,"Sandbar Shark":0.3,"Loggerhead":0.3},"Bluefin Tuna":{"Sardine":0.6,"Amberjack":0.4},"Swordfish":{"Sardine":0.5,"Cuttlefish":0.5},
"Loggerhead":{"Man o' War":0.5,"Porcelain Crab":0.2,"Moon Jelly Bloom":0.3},"Monk Seal":{"Octopus":0.4,"Slipper Lobster":0.3,"Bream":0.3},
"Sandbar Shark":{"Sea Bass":0.3,"Dentex":0.3,"Octopus":0.2,"Lost One":0.1,"Diver":0.1},"Leatherback":{"Moon Jelly Bloom":0.6,"Man o' War":0.4},
"Nile Crocodile of the Canals":{"Water Monitor":0.2,"Loggerhead":0.2,"Cistern Frog":0.1,"Lost One":0.3,"Diver":0.2},"Great White":{"Bluefin Tuna":0.3,"Monk Seal":0.2,"Sandbar Shark":0.2,"Lost One":0.1,"Diver":0.2},
"Giant Squid":{"Bluefin Tuna":0.3,"Monk Seal":0.2,"Lost One":0.2,"Diver":0.3},"The Cistern Wyrm":{"Conger Eel":0.2,"Sandbar Shark":0.2,"Nile Crocodile of the Canals":0.1,"Lost One":0.2,"Diver":0.3},
}
FOODS=["Plankton","Detritus","Corpse","Parasites","Turf on marble","Sea lettuce terraces","Posidonia meadows","Bathhouse sponges","Ichor-fed crabs","Lost One","Diver"]
FLORA=[("Posidonia meadows","Producer","Farms","Grazer base for the whole lower city; one patch is hallucinogenic (salema go erratic)",0,"Salema",1.0,90),
("Sea lettuce terraces","Producer","Farms","Farm grazers; regrows fast",0,"Bream",1.0,60),
("Column coral","Structure","Forum, Library, Chapel","Grows on every pillar; sharp corners bleed",4,"",0,0),
("Doorway kelp curtains","Cover","Every district","Hangs in doorways; hides what's inside, both ways",0,"Spider Crab (decoration)",0,0),
("Bathhouse sponges","Shelter","Bathhouses","Cardinalfish and shrimp inside; groupers and sea bass wait beside them",0,"Nudibranch",0.3,120),
("Forum sea fans","Cover","Forum","Break sightlines across the plaza",0,"",0,0),
("Temple glow-moss","Luminous producer","Chapel, Library","Lights the chapel and the library; draws squid",0,"",0.5,180),
("Amphora anemones","Hazard","Lower Town","Stings (10); an octopus is usually behind one",10,"",0,0),
("Barnacle marble","Hazard","Lower Town, Barracks","Cuts (bleed 3 s) on every wall brushed at speed",5,"",0,0),
("Fire coral on the wall","Hazard","The Wall rampart","Burns (15) along the rampart walk",15,"",0,0),
("Courtyard sargassum","Air","Courtyards","Surface air pockets in the roofless courtyards; man o' war beneath",0,"",0,0),
("Stinging hydroid drains","Hazard","Every drain grate","Every grate stings (bleed) when touched",4,"",0,0)]
# City on a hill: districts as rings/sectors. Hill centre (0,0), wall at r=240. Angles: 0 = east, 90 = north (plan).
DISTRICTS=[ # name, r_min, r_max, ang_min, ang_max, elevation_m (above wall floor), depth_m (below surface), door, notes
("Harbor Gate","Gate",228,245,255,285,0,90,0,"Start pocket in the gatehouse; Gannet rack; Juggernaut; the Lost Ones' entry through the outer gate; barracuda in the arch"),
("The Farms","Ring",165,228,190,350,5,85,750,"Terraces, canals, granaries, the mill; crocodile canals; Needler Mk I, Quick Brine, workbench; sluice trap"),
("The Lower Town","Ring",105,165,150,390,20,70,1000,"Houses, food stores, market, toolsmiths; octopi, eels, cardinalfish; Carbine + Flechette racks, Speed Brine, Locker 1, parts"),
("The Bathhouses","Sector",65,120,330,420,40,50,1250,"Baths, gymnasium, latrines; sponges, sea bass, the monitor; Double Shot, Long Speargun; caldarium dome air pocket"),
("Barracks & Armory","Sector",65,120,120,210,40,50,1500,"Drill yard, armory, stables, the wall fort; amberjacks; Trawlerman's Rifle, Bolt Harpoon, Mule Brine; Hunt staging"),
("Library & Academy","Sector",40,90,50,130,55,40,1750,"Reading halls, scroll stores, observatory; the giant squid; Kick Brine, workbench 2, Locker 2"),
("The Forum","Summit",0,45,300,480,70,30,2000,"Council chamber, treasury, courts, the open plaza; tuna and swordfish lane; power (the treasury's crystal engine); Deadeye"),
("The Grand Chapel","Summit",0,45,120,300,70,30,2500,"Nave, crypts, the god-pool; the Wyrm's pool; kraits; the Pressure Forge; Widow's Ink"),
("The Wall & Ramparts","Ring",235,245,0,360,0,90,0,"A walkable rampart around the whole city (fire coral); the lighthouse tower on the east wall (quest); great white comes over the north wall"),
]
BUILDINGS=[ # type, district, count, footprint_m, floors, hosts, contents/loot, generator rule
("Gatehouse","Harbor Gate",1,"20x14",2,"Sardine, Barracuda","Gannet rack, Juggernaut","Fixed at the south gate"),
("Customs house","Harbor Gate",1,"12x10",1,"Cardinalfish","Quest terminal 1","Beside the gatehouse"),
("Granary","The Farms",4,"10x8",1,"Bream","Food crates: 1 in 4 holds a drop bottle","Spaced along the ring road"),
("Farmhouse","The Farms",6,"8x8",1,"Cistern Frog, Aqueduct Newt","Parts in 2 of them","Beside canals"),
("Mill","The Farms",1,"10x10",2,"Salema (the hallucinogenic patch beside it)","Workbench 1, Needler Mk I rack","At the canal head"),
("Sluice house","The Farms",2,"6x6",1,"Nile Crocodile (lair at one)","Sluice trap controls","At canal junctions"),
("House (small)","The Lower Town",18,"7x7",1,"Cardinalfish (cellar); 1 in 3 has an amphora with an Octopus","Scrip caches 50-150 in cellars","Grid blocks along the radial streets"),
("House (courtyard)","The Lower Town",6,"12x12",2,"Cormorant, Man o' War, Loggerhead (courtyard sargassum air)","Air pocket; 1 in 2 has a Monk Seal","One per block, roofless"),
("Food store","The Lower Town",4,"8x8",1,"Slipper Lobster, Scorpionfish","Ammo caches","Around the market square"),
("Market square","The Lower Town",1,"30x30 open",0,"Cuttlefish, Sardine, Dentex","Speed Brine, Locker spot 1","Centre of the Lower Town"),
("Toolsmith","The Lower Town",3,"9x7",1,"Mantis Shrimp (in the anvil)","Build parts; Carbine rack in one, Flechette rack in another","The toolsmiths' street, west side"),
("Bath (hot/cold)","The Bathhouses",3,"18x12",1,"Sea Bass, Cardinalfish in sponges, Cleaner Goby at the drains","Double Shot in the caldarium; air pocket in its dome","Terraced up the east slope"),
("Gymnasium","The Bathhouses",1,"24x16",1,"Water Monitor (hypocaust dry rooms)","Long Speargun rack","Beside the baths"),
("Latrines","The Bathhouses",1,"8x6",1,"Conger Eel (drain)","A cistern grate","Downhill of the baths"),
("Barrack block","Barracks & Armory",3,"16x8",2,"Amberjack (drill yard between them)","Trawlerman's Rifle rack, Mule Brine","Around the drill yard"),
("Armory","Barracks & Armory",1,"12x10",1,"Lost Ones' garrison (Hunt staging)","Bolt Harpoon rack; armor parts","North side of the yard"),
("Stables","Barracks & Armory",1,"14x8",1,"Spider Crab, Slipper Lobster","Parts","West side"),
("Wall fort","The Wall & Ramparts",1,"12x12",3,"Barracuda","Quest terminal 2","On the west wall"),
("Reading hall","Library & Academy",2,"20x12",2,"Giant Squid (the stacks), Cardinalfish","Kick Brine, workbench 2","Facing the plaza"),
("Scroll store","Library & Academy",2,"10x8",1,"Cardinalfish, Temple Krait","Locker spot 2, quest terminal 3","Behind the halls"),
("Observatory","Library & Academy",1,"10x10 round",3,"Cormorant (open roof)","Air pocket; a view of the whole plaza","Highest point of the district"),
("Council chamber","The Forum",1,"22x14",2,"Feather Star, Moon Jelly","Deadeye Brine","North of the plaza"),
("Treasury","The Forum",1,"14x14",1,"Leatherback (it lives in the plaza pool)","Power: the crystal engine; quest terminal 4","East of the plaza"),
("Courts","The Forum",1,"16x12",1,"Sea Bass","Ammo cache","West of the plaza"),
("The Plaza","The Forum",1,"40x40 open",0,"Bluefin Tuna, Swordfish (the lane), Moon Jelly Bloom","The open sightline; the Priest's ground","Summit centre, forum side"),
("Nave","The Grand Chapel",1,"30x16",3,"Temple Krait, Cardinalfish","The Pressure Forge (in the apse); Widow's Ink","Summit centre, chapel side"),
("Crypts","The Grand Chapel",1,"20x20 (under the nave)",1,"Temple Krait, Conger Eel","Quest terminal 5; a cistern grate","Below the nave"),
("God-pool","The Grand Chapel",1,"16x16 pool",0,"The Cistern Wyrm's home","The god-pool trap (drains and refills)","Behind the apse"),
("Lighthouse","The Wall & Ramparts",1,"8x8",4,"Cormorant","The hidden quest: rekindle it to reveal the city on the sonar","East wall"),
]
AQUEDUCT=[ # segment, from, to, length_m, flow_s (blood transit), note
("A1","The summit spring (Chapel)","The Library",60,20,"Open channel along the plaza's edge"),("A2","The Library","The Bathhouses",80,25,"Arches over the east slope"),
("A3","The Bathhouses","The Lower Town (market cistern)",90,30,"Feeds the market cistern; every bath drain joins it"),("A4","The Lower Town","The Farms (canal head at the mill)",70,25,"Becomes the canals"),
("A5","The Farms","The Harbor Gate (outfall)",60,20,"Outfall through the wall; blood leaves the city here (the barracuda's dinner bell)")]
GRATES=[ # id, district, x, y, note
("G1","The Farms",-60,-190,"Canal junction"),("G2","The Lower Town",-90,-120,"Toolsmiths' street"),("G3","The Lower Town",70,-115,"Behind the food stores"),("G4","The Lower Town",0,-135,"Market square (the largest grate)"),
("G5","The Bathhouses",100,-30,"Latrines"),("G6","The Bathhouses",80,20,"Cold bath drain"),("G7","Barracks & Armory",-95,-20,"Drill yard"),("G8","Barracks & Armory",-100,40,"Stables"),
("G9","Library & Academy",20,70,"Behind the scroll stores"),("G10","The Forum",-20,20,"Plaza edge"),("G11","The Grand Chapel",10,-25,"The crypts"),("G12","The Grand Chapel",0,-40,"The god-pool itself")]
ZONES=[(d[0],d[1],d[2],d[3],d[4],d[5],d[8],d[7],d[9]) for d in DISTRICTS]  # reuse for the generic sheet: name, level, r_min, r_max, ang_min, ang_max, door, depth, notes
LINKS=[("Harbor Gate","The Farms",750,"The inner gate"),("The Farms","The Lower Town",1000,"Three radial stairs (any one)"),("The Lower Town","The Bathhouses",1250,"The bath stairs (east)"),
("The Lower Town","Barracks & Armory",1500,"The garrison gate (west)"),("The Bathhouses","Library & Academy",1750,"The academy steps"),("Barracks & Armory","Library & Academy",0,"The parade stair (opens with the garrison gate)"),
("Library & Academy","The Forum",2000,"The plaza gate"),("The Forum","The Grand Chapel",2500,"The chapel doors"),("Harbor Gate","The Wall & Ramparts",0,"Rampart stair (always open)"),("The Wall & Ramparts","The Farms",0,"Rampart stairs at 4 points (one-way down)"),
("Barracks & Armory","The Wall & Ramparts",0,"The wall fort")]
POI=[("Gannet rack","Rack","Harbor Gate",-10,-238),("Juggernaut Brine","Tonic","Harbor Gate",12,-232),("Barracuda arch","Hazard","Harbor Gate",0,-244),("Quest terminal 1","Quest","Harbor Gate",-24,-232),
("Needler Mk I rack","Rack","The Farms",-30,-200),("Quick Brine","Tonic","The Farms",60,-205),("Workbench 1 (mill)","Build","The Farms",-40,-185),("Sluice trap","Trap","The Farms",-70,-175),("Crocodile lair","Hazard","The Farms",90,-185),("Hallucinogenic meadow","Feature","The Farms",-10,-210),
("Speed Brine (market)","Tonic","The Lower Town",-15,-140),("Locker spot 1 (market)","Locker","The Lower Town",15,-140),("Sea-Pattern Carbine rack","Rack","The Lower Town",-110,-90),("Flechette 12 rack","Rack","The Lower Town",-120,-60),("Octopus dens (amphora streets)","Hazard","The Lower Town",60,-130),("Sandbar shark patrol","Hazard","The Lower Town",-60,-100),
("Double Shot (caldarium)","Tonic","The Bathhouses",95,-10),("Long Speargun rack (gymnasium)","Rack","The Bathhouses",110,-40),("Caldarium dome air pocket","Feature","The Bathhouses",90,0),("Monitor hypocaust","Hazard","The Bathhouses",105,-55),("Cleaning station (bath drains)","Feature","The Bathhouses",75,25),
("Trawlerman's Rifle rack","Rack","Barracks & Armory",-95,-60),("Bolt Harpoon rack (armory)","Rack","Barracks & Armory",-110,0),("Mule Brine","Tonic","Barracks & Armory",-80,30),("Lost Ones Hunt staging","Entry","Barracks & Armory",-110,-30),("Wall fort (quest terminal 2)","Quest","Barracks & Armory",-235,10),
("Kick Brine","Tonic","Library & Academy",50,60),("Workbench 2","Build","Library & Academy",30,50),("Locker spot 2","Locker","Library & Academy",10,80),("The stacks (giant squid)","Boss","Library & Academy",60,80),("Quest terminal 3","Quest","Library & Academy",-10,85),
("Power: the crystal engine (treasury)","Power","The Forum",35,10),("Deadeye Brine (council)","Tonic","The Forum",-5,40),("The plaza (tuna lane)","Feature","The Forum",-20,15),("Quest terminal 4","Quest","The Forum",40,20),
("Pressure Forge (apse)","Forge","The Grand Chapel",0,-20),("Widow's Ink","Tonic","The Grand Chapel",-30,-15),("God-pool (Wyrm's home)","Boss","The Grand Chapel",0,-40),("God-pool trap","Trap","The Grand Chapel",15,-40),("Quest terminal 5 (crypts)","Quest","The Grand Chapel",-15,-30),
("Lighthouse (quest)","Quest","The Wall & Ramparts",238,0),("Great white's crossing (north wall)","Hazard","The Wall & Ramparts",0,238),("Aqueduct outfall","Feature","Harbor Gate",30,-236)]
SPAWN=[("Harbor Gate","Sardine",40,20),("Harbor Gate","Barracuda",1,300),("Harbor Gate","Cardinalfish",6,90),
("The Farms","Bream",30,30),("The Farms","Salema",40,30),("The Farms","Cistern Frog",8,180),("The Farms","Aqueduct Newt",10,120),("The Farms","Spider Crab",3,300),("The Farms","Nile Crocodile of the Canals",1,0),("The Farms","Amberjack",6,300),
("The Lower Town","Sardine",80,20),("The Lower Town","Cardinalfish",20,90),("The Lower Town","Snapping Shrimp",1,0),("The Lower Town","Porcelain Crab",12,90),("The Lower Town","Sea Cucumber",8,120),("The Lower Town","Long-spined Urchin",15,120),("The Lower Town","Scorpionfish",4,0),("The Lower Town","Cuttlefish",3,240),("The Lower Town","Slipper Lobster",4,180),("The Lower Town","Mantis Shrimp",3,300),("The Lower Town","Octopus",6,600),("The Lower Town","Dentex",4,300),("The Lower Town","Sandbar Shark",1,600),
("Courtyards","Cormorant",10,120),("Courtyards","Man o' War",3,240),("Courtyards","Loggerhead",1,500),("Courtyards","Monk Seal",1,600),
("The Bathhouses","Cleaner Goby",4,300),("The Bathhouses","Nudibranch",4,180),("The Bathhouses","Sea Bass",3,300),("The Bathhouses","Water Monitor",1,600),("The Bathhouses","Cardinalfish",15,90),
("Barracks & Armory","Amberjack",6,300),("Barracks & Armory","Spider Crab",2,300),("Barracks & Armory","Slipper Lobster",3,180),
("Library & Academy","Giant Squid",1,0),("Library & Academy","Cardinalfish",12,90),("Library & Academy","Temple Krait",2,300),
("The Forum","Feather Star",6,0),("The Forum","Moon Jelly Bloom",1,180),("The Forum","Bluefin Tuna",3,400),("The Forum","Swordfish",1,500),("The Forum","Leatherback",1,0),("The Forum","Sea Bass",1,300),
("The Grand Chapel","Temple Krait",3,300),("The Grand Chapel","Cardinalfish",10,90),("The Grand Chapel","The Cistern Wyrm",1,0),
("Cisterns","Conger Eel",6,360),("Cisterns","Lamprey",4,120),("Cisterns","Cistern Frog",10,180),
("Beyond the wall","Great White",1,900)]
NOTES=["The generator: place districts by (r, angle) on the hill; lay three radial avenues (S gate -> plaza, E baths -> plaza, W garrison -> plaza) and two ring roads (r=165, r=105); fill each district with its building types by count, footprints snapped to the street grid; run the aqueduct A1-A5; drop 12 cistern grates at the listed points; decorate by habitat rules.",
"Training loop (streets): Market square -> toolsmiths' street -> garrison gate -> drill yard -> parade stair -> plaza -> bath stairs -> caldarium -> bath stairs down -> market. About 4 min, all on cobbles, past two grates.",
"Training loop (walls): the whole rampart, 1,500 m, one-way stairs down into the Farms at four points; nothing lives on the wall but barracuda at the gate and cormorants; the great white crosses the north wall.",
"Blood flow: the aqueduct carries blood downhill at the segment speeds (summit to gate in about 2 minutes); the plaza's blood reaches the market in 75 s and the barracuda at the outfall in 120 s.",
"Sightlines: streets 10-15 m; the plaza 40 m; the drill yard 25 m; ramparts 60 m+. Alarm regions: Summit (Forum, Chapel, Library), Slopes (Baths, Barracks), Lower (Town, Farms, Gate); the Lost Ones enter at the outer gate and stage at the armory.",
"Ichor: dead Lost Ones repel sharks and the Wyrm for 60 s within 20 m and draw crabs, cucumbers, and the monitor. A phalanx killed in a street makes that street a safe corridor for a minute and a monitor's dinner for two."]
BOSS=["The Cistern Wyrm — a conger the length of a street living in the cistern network under every district. Arena: the chapel's god-pool until tide 12; after that any of the 12 grates, so the city is the arena.",
"HP 15,000 (x1.08 per tide); armor: only the head is exposed above a grate; weak point: the gills, exposed when it surfaces fully (Surface strike, 2 s after) and when the god-pool trap strands it (6 s).",
"Phase 1 (100-60%): Surface strike from the god-pool and the two chapel grates (G11, G12); Drag below (a diver pulled into the drains: teammates have 6 s to deal 200 to the gills at the grate). It never leaves the summit in phase 1.",
"Phase 2 (60-30%): it uses every grate in the current district and the district below it (blood flows downhill, and so does it); Coil loops a street and blocks it 4 s; congers pour from the other grates.",
"Phase 3 (30-0%): Flood: every grate in the district surges (slow 30%, blood doubled), which calls the great white over the wall onto whatever is bleeding; it surfaces fully to hunt the streets and can be fought like a normal beast, but its blood in the aqueduct brings the great white to it as well as to you.",
"Arena rules: the god-pool trap (1,000) drains the pool and strands it for 6 s if it's home; netting three of a district's grates forces it to surface at the fourth (predictable); ichor-scented streets (dead Lost Ones) keep it below for 60 s.",
"Kill reward: 1,500 base scrip x tide, a Locker weapon each, and the lighthouse key. It reforms in the god-pool after 6 minutes at 50% HP."]
FACTION=dict(name="The Lost Ones",intro="Drowned citizens of Atlantis who breathe water and kept their discipline: legionnaires who fight in phalanx, cultists who chant, slingers, and a priest who can call the Alien Horror. They bleed black ichor, a scent the city's scavengers love and its apex beasts avoid, so a street of their dead is briefly safe from sharks and full of crabs.",
units=[("Legionnaire",200,"Gladius and tower shield","35 melee, 1.0 s; shield blocks frontal shots (400 shield HP)","Slow (1.2)","Phalanx: three in a line block a street; the middle one advances","Shields knock together twice before an advance","Gladius (melee), 260"),
("Slinger",120,"Sling","30, one stone per 2 s, 20 m","Diver speed","Fires over the phalanx; targets reloading divers","Whirls the sling","Sling stones (tactical), 220"),
("Cultist",130,"Void chant","0; chant slows divers 30% in 10 m and adds 5 nerves per s","Diver speed","Chants behind the line; on losing, chants to call the Alien Horror (Hunts only)","Arms raised, a violet glow","A void charm (one Salt Charm), 240"),
("Armored Lost One (Hunts)",700,"Titan shield","Shield crush 90, 40% stun","Slow (1.0)","An immovable wall: blocks a street entirely; must be flanked","Plants the shield; stone dust","Armor plate (build part), 500"),
("The Priest (Hunts)",600,"The sigil","0","Slow","Stands in the plaza; after 60 s of chanting the Alien Horror (Depth's mini-boss: 2,500 HP, teleports one diver 20 m every 8 s) arrives for 90 s","A sigil drawn in ichor on the plaza floor","The sigil (calls the Horror once as a diver's item), 600")],
tactics=["A squad enters at the outer gate and marches up a radial avenue in phalanx; it holds plazas and yards rather than chasing through houses; it knows every grate and never stands on one.",
"On contact: Legionnaires lock shields across the street; Slingers fire over them; the Cultist chants from behind; the line advances one step every 3 s. Flank through a house or a courtyard, or drop a Legionnaire's shield with a limpet.",
"They fight beasts that nest in their old homes (octopi, congers) and avoid the Wyrm; they never enter the farms' canals (the crocodile) and treat the library as forbidden.",
"Ink and chum do nothing to them (they smell ichor, not blood); nets hold them 4 s; a flooded terrace (the sluice trap) drowns a phalanx because they can't swim up in armor.",
"In a Hunt the Armored Lost One holds the avenue while the Priest chants in the plaza; killing the Priest before 60 s prevents the Horror; leading a phalanx onto the plaza lane during a tuna crossing breaks it."],
barks=["Spotting: 'Strangers in the forum.' / 'They breathe air. Pity them.'","Phalanx: 'Shields. Step.' / 'The line holds; the city holds.'","Losing: 'Priest! The old one!' / 'Sing them under.'","A Legionnaire dies: 'Back to the pool with you.'","The Wyrm surfaces: 'Off the grates! It's the god's own.'","Priest: 'The sigil is drawn. Kneel or be unmade.'"])
ZONE_HEADER=["district","shape","r_min_m","r_max_m","angle_min_deg","angle_max_deg","door_cost_scrip","depth_m","notes"]
