# Sunken Ship species data. Fields beyond the doc's tables are set here.
MAP="The Sunken Ship"; SLUG="ship"
SIZE={1:dict(hp=20,bounty=40,blood=20,bps=2,speed=2.2,turn=360),2:dict(hp=60,bounty=80,blood=40,bps=4,speed=2.0,turn=300),
3:dict(hp=250,bounty=180,blood=60,bps=6,speed=1.8,turn=180),4:dict(hp=900,bounty=400,blood=80,bps=8,speed=2.4,turn=120),
5:dict(hp=3000,bounty=900,blood=100,bps=10,speed=2.6,turn=70),6:dict(hp=15000,bounty=1500,blood=120,bps=12,speed=1.2,turn=40),7:dict(hp=999999,bounty=0,blood=0,bps=0,speed=3.0,turn=10)}
# (name, class, size, tier, tags, archetype, social, group, home_zone, home_flora, defend_r, threshold, aggr, fear, cur,
#  sight, scent, hear, electro, weak_point, armor_front, attacks[(name,dmg,windup_s,cooldown_s,range_m,tell,effect)], special, drop%)
S=[
("Bilge Sprat","Fish",1,1,"schooler","Schooler","school",25,"Salon","","",0,0.0,0.9,0.2,15,10,20,0,"none",0,[],"Flashes silver when the school breaks; 20 sprats = one shark's blood",1),
("Silverside","Fish",1,1,"schooler","Schooler","school",30,"Keel","Bladder kelp","",0,0.0,0.9,0.2,15,10,20,0,"none",0,[],"School outside the hull; flashes draw barracuda by sight",1),
("Sergeant Major","Fish",1,1,"territorial","Territorial","pair",2,"Keel","Turf algae",3,0,0.3,0.6,0.3,12,8,10,0,"none",0,[("Nip",2,0.3,1.0,1,"Darts at the visor","")],"Guards egg patches on the hull",1),
("Barnacle Goby","Fish",1,1,"","Grazer","solo",1,"Cabins","","",0,0.0,0.9,0.2,8,6,10,0,"none",0,[],"Lives in pipes; the sea snake's prey",1),
("Cleaner Wrasse","Fish",1,0,"cleaner","Grazer","solo",1,"Galley","","",0,0.0,0.6,0.5,10,8,10,0,"none",0,[],"Cleaning station in the galley: hosts within 6 m lose 20% aggression; killing it raises host aggression 20% map-wide for 5 min",0),
("Cleaner Shrimp","Crustacean",1,0,"cleaner","Grazer","group",6,"Galley","Barrel sponge","",0,0.0,0.6,0.5,6,6,6,0,"none",0,[],"Brushes parasites off a diver who holds still 3 s",0),
("Fiddler Crab","Crustacean",1,1,"","Grazer","group",8,"Keel","","",0,0.0,0.9,0.2,8,6,8,0,"underside",1,[],"Waves a claw when a predator is within 20 m (free warning)",2),
("Hermit Crab","Crustacean",1,1,"scavenger","Grazer","group",6,"Keel","","",5,0.0,0.7,0.3,6,15,6,0,"underside",1,[],"Eats corpses: 0.5 blood/s removed per crab",2),
("Whelk","Mollusc",1,1,"","Grazer","solo",1,"Keel","Coralline crust","",0,0.0,0.2,0.1,3,4,3,0,"none",1,[],"Slow; free scrip",3),
("Sea Hare","Mollusc",2,1,"toxic","Grazer","solo",1,"Salon","Sea lettuce","",0,0.0,0.5,0.2,5,6,5,0,"none",0,[],"Inks when shot: an 8 s ink cloud (cuts sight and scent)",3),
("Feather Duster Worm","Worm",1,1,"sessile","Grazer","solo",1,"Cabins","","",0,0.0,1.0,0.0,6,0,8,0,"none",0,[],"Retracts when anything passes within 2 m: a motion sensor",0),
("Rudder Krill","Crustacean",1,1,"swarm","Swarmer","swarm",200,"Engine","Luminous algae mat","",0,0.0,0.8,0.5,4,4,4,0,"none",0,[],"One agent, 200 bodies; shooting it is loud and pointless",0),
("Parrotfish","Fish",2,1,"","Grazer","group",4,"Keel","Turf algae","",0,0.0,0.8,0.2,12,8,12,0,"gills",0,[],"Crunch = 3 noise every 4 s (draws barracuda); sleeps in a cocoon in cabins at night tides",3),
("Rabbitfish","Fish",2,1,"venom","Grazer","group",5,"Salon","Sea lettuce","",0,0.0,0.8,0.2,12,8,12,0,"gills",0,[("Spine",8,0,0,0.5,"","Touch: poison 4 s")],"Venomous dorsal spines on contact",3),
("Damselfish","Fish",1,2,"territorial","Territorial","group",6,"Keel","Turf algae",4,0,0.6,0.3,0.4,10,6,10,0,"none",0,[("Bite",1,0.2,0.5,1,"Rushes in","")],"A swarm of 1-damage bites inside its patch",2),
("Blenny","Fish",1,2,"","Ambusher","solo",1,"Cabins","","",0,0.2,0.8,0.3,8,6,8,0,"none",0,[],"Pipe-dweller; harmless",2),
("Arrow Crab","Crustacean",1,2,"","Grazer","solo",1,"Cabins","Sea fan","",0,0.0,0.7,0.3,6,6,6,0,"underside",1,[],"On sea fans; harmless",2),
("Mantis Shrimp","Crustacean",2,2,"burrower","Ambusher","solo",1,"Keel","","",10,0.5,0.4,0.3,8,8,8,0,"eyes",2,[("Punch",30,0.4,2.0,1.5,"Antennae flick up","Breaks a Shell Shield in 2 hits")],"Burrows in sand; strikes from the hole",4),
("Lionfish","Fish",2,2,"venom","Patroller","solo",1,"Cabins","","",10,0.3,0.4,0.3,10,10,10,0,"belly",0,[("Spines",20,0,0,0.6,"","Contact: poison 5 s")],"Drifts through doorways; venom on contact",4),
("Squirrelfish","Fish",2,2,"nocturnal","Patroller","group",3,"Cabins","","",10,0.2,0.7,0.4,14,8,14,0,"eyes",0,[],"Night tides only; loud clicks (2 noise)",3),
("Reef Squid","Cephalopod",2,2,"","Schooler","school",8,"Keel","Dead man's fingers","",10,0.2,0.8,0.7,14,8,10,0,"mantle",0,[],"Inks when threatened; drawn to dead man's fingers",3),
("Cuttlefish","Cephalopod",2,2,"camouflage","Ambusher","solo",1,"Cabins","","",10,0.3,0.6,0.5,12,8,8,0,"mantle",0,[("Flash",0,0.5,6.0,4,"Skin ripples","Diver aim sway +30% for 3 s")],"Camouflaged; hypnotic flashing",4),
("Banded Sea Snake","Reptile",2,2,"venom,air-breather","Patroller","solo",1,"Cabins","","",15,0.5,0.4,0.5,10,10,8,0,"head",0,[("Bite",10,0.5,2.0,1,"Coils back","Poison 20 over 10 s")],"Must surface at the salon air pocket every 90 s",5),
("Stonefish","Fish",2,2,"venom,camouflage","Ambusher","solo",1,"Galley","","",0,0.0,0.0,0.0,4,4,4,0,"belly",3,[("Spines",40,0,0,0.6,"","Contact: poison 8 s")],"Invisible until stepped on; never moves",5),
("Jelly Bloom","Cnidarian",2,1,"swarm,venom","Swarmer","swarm",40,"Stern","Sargassum raft","",0,0.0,0.0,0.0,0,0,0,0,"none",0,[("Sting",5,0,1.0,1,"","Contact: 5/s")],"Drifts under the sargassum and into the stern",0),
("Remora","Fish",1,0,"parasite","Parasite","solo",1,"Keel","","",5,0.0,0.6,0.8,10,10,8,0,"none",0,[("Attach",0,0.3,0,0.5,"Swims alongside","Diver swim speed -15% until brushed")],"Rides sharks, turtles, divers",1),
("Lamprey","Fish",2,0,"parasite","Parasite","solo",1,"Engine","","",10,0.4,0.4,0.6,10,15,8,0,"none",0,[("Latch",2,0.5,0,0.5,"Circles the target","Host bleeds 2/s; host becomes a blood source")],"Prefers wounded hosts",2),
("Green Moray","Fish",3,3,"territorial","Ambusher","solo",1,"Cabins","Sea fan",3,30,0.7,0.2,0.2,8,20,10,0,"gills",1,[("Strike",35,0.4,1.5,2,"Mouth opens wide","Bleed 3 s"),("Hold",15,0.6,4.0,1.5,"Body straightens","Holds 2 s")],"Strikes 2 m from its pipe, retreats after 3 attacks",6),
("Great Barracuda","Fish",3,3,"","Patroller","solo",1,"Salon","","",30,0.6,0.3,0.7,25,20,20,0,"gills",0,[("Slash",30,0.3,1.2,2,"Straightens and accelerates","Bleed 3 s"),("Hit-and-run",45,0.5,4.0,10,"Circles wide","Passes through; no hold")],"Drawn to flashes (silversides, gunfire flash, lamps) and the parrotfish crunch",6),
("Grouper","Fish",3,3,"","Ambusher","solo",1,"Engine","","",30,0.6,0.3,0.3,10,25,10,0,"gills",1,[("Gulp",40,0.6,2.5,2,"Gills flare","Swallows size 1 whole; on a diver: 40 and 1 s hold")],"Waits in engine-room shadows",6),
("Bluefin Trevally","Fish",3,3,"pack","Pack hunter","pack",5,"Keel","","",30,0.7,0.3,0.5,25,20,20,0,"gills",0,[("Ram",25,0.4,1.5,3,"Pack fans out","Knocks a diver 2 m")],"Drives schools against the hull; flank and drive roles",6),
("Common Octopus","Cephalopod",3,3,"thief","Ambusher","solo",1,"Cabins","Barrel sponge","",30,0.4,0.6,0.9,10,15,8,0,"mantle",0,[("Grab",20,0.5,3.0,2.5,"Arm extends","Steals a held part or charm, then flees home")],"Kill it in its den to get the item back",8),
("Nurse Shark","Fish",3,0,"scavenger,nocturnal","Grazer","solo",1,"Keel","","",15,0.2,0.4,0.4,12,30,10,4,"gills",1,[("Bite",30,0.6,3.0,1.5,"Only if shot","")],"Eats corpses at 3 blood/s: the map's best cleanup; docile",5),
("Hawksbill Turtle","Reptile",3,2,"armored","Grazer","solo",1,"Stern","Barrel sponge","",0,0.1,0.5,0.3,12,10,10,0,"neck",3,[("Bite",25,0.6,3.0,1,"Only if shot","")],"Eats sponges and the jelly bloom",5),
("Loggerhead Turtle","Reptile",4,3,"armored","Grazer","solo",1,"Keel","","",0,0.2,0.4,0.3,12,12,10,0,"neck",4,[("Crush",60,0.8,4.0,1.2,"Head draws back","Destroys a Shell Shield")],"Eats crabs, whelks, mantis shrimp",6),
("Sand Tiger Shark","Fish",4,4,"","Wanderer","solo",1,"Keel","","",60,0.6,0.1,0.5,20,40,20,6,"gills",1,[("Bite",70,0.5,2.0,2,"Mouth gapes, ragged teeth","Bleed 4 s"),("Thrash",40,0.4,3.0,2.5,"Tail sweeps","Knockback 3 m")],"Hangs motionless near the keel; investigates blood over 60",8),
("Bull Shark","Fish",4,4,"","Wanderer","solo",1,"Stern","","",80,0.9,0.1,0.6,20,45,25,6,"gills",1,[("Bite",80,0.4,1.8,2,"Pectorals drop","Bleed 4 s"),("Ram",50,0.5,3.0,6,"Straight line charge","Knockback 4 m, stun 1 s"),("Hold",30,0.6,5.0,1.5,"Head shakes","Holds 2 s; teammates must shoot it off")],"Enters through the breach; aggressive; attacks Wreckers on sight",8),
("Saltwater Crocodile","Reptile",5,4,"amphibious,armored","Territorial","solo",1,"Salon","",8,100,0.8,0.1,0.3,15,35,20,0,"throat",4,[("Death Roll",120,0.9,6.0,2.5,"Rises from the air pocket, jaws open","Holds and rolls; teammates have 4 s"),("Snap",60,0.4,2.0,2,"Jaw clicks","Bleed 3 s"),("Tail",45,0.5,3.0,3,"Turns side-on","Knockback 4 m")],"Lives in the salon air pocket; eats turtles, bull sharks, Wreckers; leaves for the sand when the pocket shrinks",10),
("Tiger Shark","Fish",5,4,"","Wanderer","solo",1,"Outside","","",150,0.9,0.0,0.7,30,80,30,8,"gills",1,[("Bite",110,0.5,2.0,2.5,"Rolls to one side","Bleed 5 s"),("Ram",70,0.5,4.0,8,"Straight charge","Knockback 5 m, stun 1 s"),("Drag",50,0.7,8.0,2,"Grabs and swims","Carries a diver 10 m; teammates shoot it off")],"Follows blood from anywhere on the map; eats enemies as readily as divers; leaves when fed",10),
("The Goliath","Fish",6,5,"boss","Boss","solo",1,"Engine","",12,400,1.0,0.0,0.2,20,60,20,0,"gills (behind the plates)",3,[("Inhale",0,1.5,12.0,4,"Gills close, water rushes","Pulls a diver into its mouth; 5 s to shoot it out (150 damage to the gills)"),("Tail Slam",90,0.8,5.0,4,"Turns away","Knockback 6 m; drops loose cargo"),("Boom",25,0.6,3.0,10,"Swim bladder swells","Loud 10-noise pulse: stun 1 s in 10 m"),("Lunge",140,0.7,4.0,6,"Fins flare","Bleed 5 s")],"Guards the Forge; wanders from tide 12; see the boss fight",100),
]
# Diet: predator -> {prey: weight}. Non-species food columns: Plankton, Corpse, Turf algae, Sea lettuce, Coralline crust, Barrel sponge, Luminous algae mat, Parasites
D={
"Bilge Sprat":{"Rudder Krill":0.6,"Plankton":0.4},"Silverside":{"Rudder Krill":0.5,"Plankton":0.5},"Sergeant Major":{"Turf algae":0.6,"Jelly Bloom":0.4},
"Barnacle Goby":{"Plankton":0.5,"Corpse":0.5},"Cleaner Wrasse":{"Parasites":1.0},"Cleaner Shrimp":{"Parasites":1.0},"Fiddler Crab":{"Corpse":0.4,"Turf algae":0.6},
"Hermit Crab":{"Corpse":1.0},"Whelk":{"Coralline crust":1.0},"Sea Hare":{"Sea lettuce":1.0},"Feather Duster Worm":{"Plankton":1.0},"Rudder Krill":{"Luminous algae mat":0.7,"Plankton":0.3},
"Parrotfish":{"Turf algae":1.0},"Rabbitfish":{"Sea lettuce":0.6,"Turf algae":0.4},"Damselfish":{"Feather Duster Worm":0.3,"Plankton":0.4,"Turf algae":0.3},
"Blenny":{"Feather Duster Worm":0.5,"Barnacle Goby":0.5},"Arrow Crab":{"Feather Duster Worm":1.0},"Mantis Shrimp":{"Fiddler Crab":0.5,"Whelk":0.3,"Hermit Crab":0.2},
"Lionfish":{"Bilge Sprat":0.6,"Barnacle Goby":0.4},"Squirrelfish":{"Fiddler Crab":0.5,"Hermit Crab":0.5},"Reef Squid":{"Bilge Sprat":0.5,"Silverside":0.5},
"Cuttlefish":{"Fiddler Crab":0.5,"Cleaner Shrimp":0.2,"Arrow Crab":0.3},"Banded Sea Snake":{"Barnacle Goby":0.5,"Blenny":0.5},"Stonefish":{"Bilge Sprat":1.0},
"Jelly Bloom":{"Plankton":1.0},"Remora":{"Corpse":1.0},"Lamprey":{"Great Barracuda":0.2,"Grouper":0.2,"Loggerhead Turtle":0.2,"Bull Shark":0.2,"Nurse Shark":0.2},
"Green Moray":{"Common Octopus":0.4,"Squirrelfish":0.3,"Blenny":0.3},"Great Barracuda":{"Silverside":0.4,"Reef Squid":0.3,"Bilge Sprat":0.3},
"Grouper":{"Parrotfish":0.3,"Lionfish":0.2,"Green Moray":0.2,"Cuttlefish":0.3},"Bluefin Trevally":{"Silverside":0.4,"Reef Squid":0.3,"Damselfish":0.3},
"Common Octopus":{"Fiddler Crab":0.3,"Mantis Shrimp":0.3,"Whelk":0.2,"Hermit Crab":0.2},"Nurse Shark":{"Corpse":0.7,"Fiddler Crab":0.3},
"Hawksbill Turtle":{"Barrel sponge":0.6,"Jelly Bloom":0.4},"Loggerhead Turtle":{"Fiddler Crab":0.4,"Whelk":0.3,"Mantis Shrimp":0.3},
"Sand Tiger Shark":{"Bluefin Trevally":0.4,"Great Barracuda":0.3,"Grouper":0.3},"Bull Shark":{"Bluefin Trevally":0.2,"Great Barracuda":0.2,"Grouper":0.2,"Green Moray":0.1,"Hawksbill Turtle":0.1,"Wrecker":0.2},
"Saltwater Crocodile":{"Hawksbill Turtle":0.3,"Loggerhead Turtle":0.2,"Bull Shark":0.2,"Wrecker":0.3},
"Tiger Shark":{"Sand Tiger Shark":0.15,"Bull Shark":0.15,"Loggerhead Turtle":0.15,"Banded Sea Snake":0.1,"Nurse Shark":0.1,"Wrecker":0.2,"Corpse":0.15},
"The Goliath":{"Grouper":0.3,"Green Moray":0.2,"Bull Shark":0.2,"Wrecker":0.3},
}
FOODS=["Plankton","Corpse","Parasites","Turf algae","Sea lettuce","Coralline crust","Barrel sponge","Luminous algae mat","Wrecker"]
FLORA=[("Turf algae","Producer","Keel, Stern","Grazer food; parrotfish crunch draws barracuda",0,"Parrotfish, Rabbitfish, Sergeant Major, Damselfish, Fiddler Crab",1.0,60),
("Sea lettuce","Producer","Salon","Grazer food; dies back if grazers are wiped, regrows in 90 s",0,"Sea Hare, Rabbitfish",1.0,90),
("Fire coral","Hazard","Cabins, Galley","Touch: 15 burn + flinch",15,"",0,0),
("Stinging hydroids","Hazard","Salon doorways, Cabins","Touch: bleed 3 s",4,"",0,0),
("Barrel sponge","Shelter","Galley, Stern","Hides size-1 beasts; hawksbill food",0,"Hawksbill Turtle",0.3,120),
("Sea fan","Cover","Cabins","Blocks sight; a moray or stonefish usually behind it",0,"",0,0),
("Anemone bed","Host/Hazard","Keel","Clownfish home; stings 10; holds size 1",10,"",0,0),
("Bladder kelp (mast)","Shelter/Current","Outside","Hides divers from sight; sways with current",0,"",0,0),
("Coralline crust","Producer","Keel, Stern","Whelk and sea hare food",0,"Whelk, Sea Hare",0.5,120),
("Dead man's fingers","Luminous","Stern","Glows when touched; draws squid and cuttlefish at night tides",0,"",0,0),
("Sargassum raft","Shelter","Outside (surface)","Shade; jelly bloom gathers under it",0,"",0,0),
("Luminous algae mat","Luminous producer","Engine","Krill food; lights the engine room; the Goliath's lamp",0,"Rudder Krill",1.0,60)]
ZONES=[  # name, deck, x, y, w, h (m), door cost, notes
("Bridge","Upper",4,2,10,6,0,"Start pocket. Gannet rack, Juggernaut visible below"),
("Grand Salon","Upper",16,0,20,12,750,"Air pocket (crocodile lair), Quick Brine, Needler Mk I rack, workbench"),
("Galley & Pantry","Upper",38,0,10,8,1000,"Flechette 12 rack, Locker spot 1, cleaning station"),
("Cabin Deck","Lower",16,16,24,10,1250,"Six cabins, moray pipes, Speed Brine, Long Speargun rack, Carbine rack"),
("Engine Room","Lower",42,16,14,12,1500,"Power switch, Pressure Forge, the Goliath's home, algae mat"),
("Stern & Swim Platform","Lower",58,14,10,14,1500,"Bolt Harpoon rack, Double Shot, Locker spot 2, hull breach (Wrecker entry)"),
("The Keel & Sand","Outside",0,30,70,14,2000,"Open shelf under the hull, Kick Brine, mast kelp, shark lane"),
("Foredeck (outside)","Outside",0,-8,16,6,0,"Cargo crane trap control; reached from the Bridge hatch"),
]
LINKS=[("Bridge","Grand Salon",750,"Salon door"),("Grand Salon","Galley & Pantry",1000,"Galley hatch"),("Grand Salon","Cabin Deck",1250,"Companionway stairs"),
("Cabin Deck","Engine Room",1500,"Watertight door"),("Engine Room","Stern & Swim Platform",1500,"Aft bulkhead"),("Stern & Swim Platform","The Keel & Sand",2000,"Hull breach"),
("Bridge","Foredeck (outside)",0,"Bridge hatch (always open)"),("Foredeck (outside)","The Keel & Sand",0,"Slide down the hull (one-way)"),("Galley & Pantry","Cabin Deck",0,"Dumbwaiter shaft (one-way drop)")]
POI=[  # name,type,zone,x,y
("Gannet rack","Rack","Bridge",6,4),("Juggernaut Brine","Tonic","Grand Salon",18,10),("Quick Brine","Tonic","Grand Salon",34,10),("Needler Mk I rack","Rack","Grand Salon",26,1),
("Workbench","Build","Grand Salon",30,6),("Air pocket / croc lair","Feature","Grand Salon",24,3),("Flechette 12 rack","Rack","Galley & Pantry",40,2),("Locker spot 1","Locker","Galley & Pantry",46,6),
("Cleaning station","Feature","Galley & Pantry",42,6),("Speed Brine","Tonic","Cabin Deck",20,24),("Long Speargun rack","Rack","Cabin Deck",28,17),("Sea-Pattern Carbine rack","Rack","Cabin Deck",36,24),
("Moray pipes x6","Hazard","Cabin Deck",18,20),("Power switch","Power","Engine Room",44,18),("Pressure Forge","Forge","Engine Room",52,26),("Goliath home","Boss","Engine Room",49,22),
("Bolt Harpoon rack","Rack","Stern & Swim Platform",60,16),("Double Shot","Tonic","Stern & Swim Platform",66,26),("Locker spot 2","Locker","Stern & Swim Platform",62,26),("Hull breach (Wrecker entry)","Entry","Stern & Swim Platform",67,20),
("Kick Brine","Tonic","The Keel & Sand",10,40),("Mast & bladder kelp","Feature","The Keel & Sand",30,42),("Shark lane","Feature","The Keel & Sand",60,40),("Cargo crane trap","Trap","Foredeck (outside)",8,-5),
("Captain's safe (quest)","Quest","Bridge",12,7),("Stonefish nest","Hazard","Galley & Pantry",44,1),("Mantis burrows","Hazard","The Keel & Sand",20,36)]
SPAWN=[ # zone, species, count, respawn_s
("Grand Salon","Bilge Sprat",50,20),("Grand Salon","Sea Hare",3,120),("Grand Salon","Rabbitfish",5,90),("Grand Salon","Great Barracuda",1,240),("Grand Salon","Saltwater Crocodile",1,0),("Grand Salon","Banded Sea Snake",1,300),
("Galley & Pantry","Cleaner Wrasse",2,300),("Galley & Pantry","Cleaner Shrimp",6,300),("Galley & Pantry","Stonefish",2,0),("Galley & Pantry","Bilge Sprat",30,20),
("Cabin Deck","Barnacle Goby",12,60),("Cabin Deck","Blenny",6,90),("Cabin Deck","Arrow Crab",6,120),("Cabin Deck","Feather Duster Worm",10,0),("Cabin Deck","Lionfish",3,180),("Cabin Deck","Squirrelfish",3,180),("Cabin Deck","Cuttlefish",2,240),("Cabin Deck","Green Moray",4,360),("Cabin Deck","Common Octopus",1,600),("Cabin Deck","Parrotfish",3,150),
("Engine Room","Rudder Krill",1,60),("Engine Room","Grouper",2,300),("Engine Room","Lamprey",3,240),("Engine Room","The Goliath",1,0),
("Stern & Swim Platform","Jelly Bloom",1,180),("Stern & Swim Platform","Hawksbill Turtle",1,400),("Stern & Swim Platform","Bull Shark",1,600),("Stern & Swim Platform","Reef Squid",8,120),
("The Keel & Sand","Silverside",60,20),("The Keel & Sand","Sergeant Major",6,90),("The Keel & Sand","Fiddler Crab",10,60),("The Keel & Sand","Hermit Crab",8,90),("The Keel & Sand","Whelk",8,120),("The Keel & Sand","Damselfish",8,90),("The Keel & Sand","Mantis Shrimp",3,300),("The Keel & Sand","Parrotfish",4,150),("The Keel & Sand","Remora",4,120),("The Keel & Sand","Bluefin Trevally",5,300),("The Keel & Sand","Nurse Shark",1,500),("The Keel & Sand","Loggerhead Turtle",1,500),("The Keel & Sand","Sand Tiger Shark",1,700),
("Outside","Tiger Shark",1,900)]
