MAP="The Underwater Cave"; SLUG="cave"; FILE="RedTide_UnderwaterCave_data.xlsx"
README_EXTRA=["Cave-specific: SLIPSTREAMS sheet lists the six one-way currents (8 m/s; no firing inside; beasts ride them too; the Drowned never do).",
"Depth column in Blockout is metres below the Mouth; the Dry Chambers are air (walking speed 1.2 m/s, gravity on)."]
S=[ # same field order as the ship file
("Blind Cavefish","Fish",1,1,"schooler,blind","Schooler","school",30,"Flooded Gallery","Glow mould","",0,0.0,0.9,0.2,0,8,25,0,"none",0,[],"No eyes: ignores light, follows sound; the wet web's base",1),
("Glass Shrimp","Crustacean",1,0,"cleaner","Grazer","group",8,"Flooded Gallery","Cave sponge","",0,0.0,0.6,0.5,6,6,6,0,"none",0,[],"Transparent; the cave's cleaner station lives in the Gallery sponges",0),
("Cave Krill","Crustacean",1,1,"swarm","Swarmer","swarm",300,"The Sump","Chemosynthetic mat","",0,0.0,0.8,0.5,4,4,4,0,"none",0,[],"One agent, 300 bodies over the vents",0),
("Cave Isopod","Crustacean",1,0,"scavenger","Grazer","group",10,"The Sump","","",5,0.0,0.7,0.3,4,15,4,0,"underside",1,[],"Silt scavenger: 0.3 blood/s removed each",2),
("Amphipod","Crustacean",1,1,"","Grazer","group",20,"Dry Chambers","Cave moss","",0,0.0,0.9,0.2,4,6,4,0,"none",0,[],"Pools and puddles in the dry chambers",1),
("Troglobite Crab","Crustacean",2,2,"","Grazer","group",4,"Flooded Gallery","","",10,0.2,0.6,0.4,0,10,12,0,"underside",2,[("Pinch",8,0.4,2.0,1,"Claws raise","")],"Ghost-white; clicks in the dark (1 noise)",3),
("Olm","Amphibian",2,2,"blind,electro","Patroller","solo",1,"Dry Chambers","","",10,0.2,0.7,0.5,0,8,10,8,"none",0,[],"Blind; feels a rebreather through 8 m of rock; a living sonar for everything else (its movement toward divers is visible)",3),
("Blind Newt","Amphibian",2,2,"","Grazer","group",6,"Dry Chambers","Cave moss","",5,0.1,0.8,0.3,0,6,8,0,"none",0,[],"Pool dweller; harmless",2),
("Poison Dart Newt","Amphibian",1,2,"toxic","Grazer","group",4,"Dry Chambers","Cave moss","",0,0.0,0.5,0.3,4,4,6,0,"none",0,[("Skin",10,0,0,0.5,"","Touch: poison 10 over 5 s")],"Bright even in the dark",2),
("Giant Cave Toad","Amphibian",3,3,"amphibious","Ambusher","solo",1,"Dry Chambers","",6,30,0.6,0.2,0.3,10,8,12,0,"throat",1,[("Tongue",20,0.6,4.0,5,"Throat swells","Pulls a diver into the pool: 2 s hold, then Bite"),("Bite",35,0.4,2.0,1.5,"Jaw drops","Hold 1 s")],"Sits at the pool edge; croak is a 3-noise alarm",5),
("Cave Crayfish","Crustacean",2,2,"","Territorial","group",3,"Flooded Gallery","Root tangle",3,10,0.5,0.4,0.3,6,10,8,0,"underside",2,[("Pinch",12,0.4,2.0,1,"Claws open","Bleed 2 s")],"Nests in root tangles; pinches divers who hide there",3),
("Fishing Spider","Insect (arachnid)",2,2,"","Ambusher","solo",1,"Dry Chambers","Root tangle","",10,0.5,0.5,0.4,10,4,8,0,"abdomen",0,[("Drop bite",18,0.5,3.0,3,"Silk twitches overhead","Poison 4 s")],"Runs on the surface; drops from roots",3),
("Cave Cricket","Insect",1,1,"swarm","Swarmer","swarm",80,"Dry Chambers","Cave moss","",0,0.0,1.0,0.0,4,0,15,0,"none",0,[],"Chirp swarm; goes silent when the Drowned pass (the warning)",0),
("Diving Beetle","Insect",1,2,"","Grazer","group",8,"Dry Chambers","","",0,0.0,0.8,0.5,4,4,4,0,"none",0,[],"Carries a bubble; free scrip",2),
("Giant Water Bug","Insect",2,2,"","Ambusher","solo",1,"Dry Chambers","","",10,0.5,0.4,0.3,6,4,6,0,"underside",1,[("Pierce",15,0.4,3.0,1,"Forelegs open","Bleed 4 s")],"Pierces the suit",3),
("Dragonfly Nymph","Insect",2,2,"","Ambusher","solo",1,"Dry Chambers","","",10,0.5,0.5,0.3,6,4,6,0,"underside",0,[("Jaw lunge",14,0.3,2.5,2,"Jet pulse","")],"Jet-propelled; a lunging jaw",3),
("Glowworm Colony","Insect",1,1,"luminous,sessile","Grazer","swarm",100,"The Chimney","","",0,0.0,1.0,0.0,0,0,0,0,"none",0,[],"Ceiling threads; curious species gather beneath; lights the Chimney",0),
("Firefly Squid","Cephalopod",2,2,"luminous","Schooler","school",12,"The Chimney","","",10,0.2,0.8,0.6,14,8,10,0,"mantle",0,[],"Flashes when threatened, lighting divers up for ambushers",3),
("Lanternfish","Fish",2,1,"luminous,schooler","Schooler","school",25,"The Sump","","",0,0.0,0.9,0.3,10,6,10,0,"none",0,[],"Sump school; its lights draw the gulper",1),
("Cave Anglerfish","Fish",3,3,"luminous","Ambusher","solo",1,"The Sump","","",30,0.6,0.2,0.2,12,20,8,0,"belly",1,[("Swallow",45,0.5,3.0,2,"The lure blinks twice","Pins 3 s")],"Its lure looks like a drop bottle from 15 m",6),
("Cave Eel","Fish",3,3,"","Ambusher","solo",1,"Flooded Gallery","",3,30,0.7,0.2,0.3,8,20,12,0,"gills",1,[("Strike",35,0.4,1.5,2,"Mouth opens","Bleed 3 s")],"Wall-crack ambusher; rides slipstreams to relocate",6),
("Electric Ray","Fish",3,3,"electric,burrower","Ambusher","solo",1,"The Sump","","",20,0.5,0.3,0.2,8,12,8,6,"belly",1,[("Shock",30,0.3,4.0,2,"Silt lifts","Stun 2 s; stops a Turbine")],"Buried in silt",6),
("Blind Catfish","Fish",3,3,"blind","Patroller","solo",1,"The Sump","","",25,0.6,0.3,0.4,0,35,15,0,"gills",1,[("Bite",30,0.4,1.5,1.5,"Whiskers sweep","Hold 1 s")],"First mid predator to any corpse: threshold 25",6),
("Whip Ray","Fish",3,3,"","Grazer","solo",1,"Flooded Gallery","","",0,0.1,0.5,0.3,10,10,8,0,"gills",1,[("Barb",40,0.3,3.0,2,"Tail arches","Bleed 5 s")],"Glides the Gallery; barbs if stepped on",5),
("Hagfish","Fish",2,0,"scavenger,slime","Grazer","group",3,"The Sump","","",5,0.1,0.3,0.3,4,25,4,0,"none",0,[("Slime",0,0.2,5.0,1,"Knots itself","Diver slowed 40% until brushed")],"Slimes divers who touch its corpse",2),
("Vampire Squid","Cephalopod",2,0,"scavenger","Grazer","solo",1,"The Sump","","",5,0.0,0.6,0.5,10,10,6,0,"mantle",0,[],"Sump drifter; cloak flashes when shot (a light burst that draws curious species)",3),
("Bristle Worm","Worm",2,0,"scavenger,venom","Grazer","group",5,"The Sump","Chemosynthetic mat","",5,0.1,0.4,0.2,4,15,4,0,"none",0,[("Bristles",10,0,0,0.5,"","Contact burn 10")],"Venomous bristles",2),
("Sea Spider","Crustacean-like",2,2,"","Grazer","solo",1,"Flooded Gallery","White anemone cluster","",0,0.0,0.4,0.2,4,4,4,0,"none",0,[],"Slow; hollow; ignores divers",2),
("Cave Swiftlet","Bird",1,2,"flying","Schooler","school",20,"Dry Chambers","","",0,0.0,1.0,0.2,20,0,25,0,"none",0,[],"Flies in the dry chambers; a startled flock is a 6-noise alarm",1),
("Snapping Turtle","Reptile",3,3,"armored","Ambusher","solo",1,"Dry Chambers","Stone lettuce",2,20,0.5,0.1,0.2,8,8,8,0,"neck",4,[("Snap",60,0.5,3.0,1.2,"Neck extends","Hold 2 s")],"Sits still in the pools",5),
("Cave Krait","Reptile",2,2,"venom,air-breather","Patroller","solo",1,"Dry Chambers","","",15,0.5,0.4,0.5,10,10,8,0,"head",0,[("Bite",10,0.5,2.0,1,"Coils","Poison 25 over 10 s")],"Swims between pools; surfaces to breathe",5),
("Epaulette Shark","Fish",3,3,"amphibious","Ambusher","solo",1,"Dry Chambers","","",30,0.6,0.3,0.4,10,20,10,4,"gills",1,[("Bite",35,0.4,2.0,1.5,"Fins plant on rock","Bleed 3 s")],"Walks on its fins across dry rock between pools",6),
("Current Runner","Fish",3,3,"fast","Patroller","solo",1,"Slipstreams","","",30,0.7,0.2,0.4,25,15,15,0,"gills",0,[("Slash",40,0.3,2.0,2,"A shadow in the stream","Bleed 3 s; knocks a diver out of the stream")],"Lives in the slipstreams; hits divers riding them",6),
("Cave Sturgeon","Fish",4,1,"armored","Grazer","solo",1,"The Sump","Stone lettuce","",0,0.1,0.6,0.2,8,10,10,0,"belly",4,[],"Harmless armored grazer; 80 blood if killed: the sump's trap",4),
("Gulper Eel","Fish",4,3,"","Ambusher","solo",1,"The Sump","","",40,0.6,0.2,0.3,10,25,10,0,"belly",1,[("Engulf",80,0.6,4.0,3,"Jaw unfolds","Pins 3 s")],"Swallows size 2 whole",7),
("Giant Salamander","Amphibian",4,4,"amphibious","Ambusher","solo",1,"Dry Chambers","",5,50,0.8,0.1,0.2,8,20,12,0,"throat",2,[("Bite and drag",70,0.6,3.0,2,"Water surges at the ledge","Hold 3 s; drags toward the pool"),("Tail",40,0.4,3.0,2.5,"Body curls","Knockback 3 m")],"Under the pool ledges",8),
("Cave Caiman","Reptile",4,4,"amphibious,armored","Patroller","solo",1,"Dry Chambers","",6,60,0.8,0.1,0.3,12,30,15,0,"throat",4,[("Bite",80,0.5,2.0,2,"Jaws part","Bleed 4 s"),("Death roll",100,0.9,6.0,2,"Grabs and spins","Hold and roll 4 s; teammates shoot it off"),("Tail",45,0.5,3.0,3,"Turns side-on","Knockback 4 m")],"Walks both webs; attacks the Drowned by habit (cold things)",8),
("Sleeper Shark","Fish",5,4,"","Wanderer","solo",1,"The Sump","","",120,0.7,0.0,0.3,10,80,10,8,"gills",1,[("Bite",150,0.6,3.0,2.5,"Silt clouds behind it","Bleed 5 s"),("Drag",60,0.8,8.0,2,"Slow turn toward a diver","Carries 10 m into the silt")],"Slow, silent, cold; nearly invisible in silt; threshold 120",10),
("Ghost Worm","Worm",4,4,"wall-dweller","Territorial","solo",1,"The Squeeze","",8,60,0.9,0.0,0.2,10,20,15,10,"mouth",3,[("Lunge",70,0.5,2.5,4,"Wall cracks glow","Bleed 4 s"),("Screech",20,0.6,6.0,8,"Head rears","Stun 1 s in 8 m; 8 noise")],"From Depth's Cave: attacks the Drowned on sight and any diver who shoots it; lives in the walls between the Gallery and the Sump",8),
("Silt Lamprey","Fish",1,0,"parasite","Parasite","solo",1,"The Sump","","",10,0.4,0.4,0.6,6,15,6,0,"none",0,[("Latch",1,0.5,0,0.5,"Circles","Host bleeds 1/s")],"Sump parasite",1),
("The Lobster","Crustacean",6,5,"boss,armored","Boss","solo",1,"The Cathedral","",14,400,1.0,0.0,0.2,15,50,20,0,"underside (when reared)",3,[("Crush",130,0.8,4.0,3,"Claw raises","Destroys a Shell Shield; hold 2 s"),("Sweep",80,0.6,5.0,5,"Turns broadside","Knockback 6 m"),("Clack",25,0.5,3.0,10,"Antennae flick","10 noise; stun 1 s; drops stalactites in phase 3"),("Rear",0,1.2,12.0,0,"Rises on its tail when the coral rings","Underside exposed 3 s")],"From Depth's Cave; the crystal coral calls it; see Boss",100),
]
D={
"Blind Cavefish":{"Glow mould":0.8,"Plankton":0.2},"Glass Shrimp":{"Parasites":0.7,"Detritus":0.3},"Cave Krill":{"Chemosynthetic mat":1.0},"Cave Isopod":{"Corpse":0.8,"Detritus":0.2},
"Amphipod":{"Detritus":0.6,"Cave moss":0.4},"Troglobite Crab":{"Amphipod":0.5,"Glass Shrimp":0.5},"Olm":{"Amphipod":0.6,"Cave Isopod":0.4},"Blind Newt":{"Amphipod":0.5,"Cave Cricket":0.3,"Diving Beetle":0.2},
"Poison Dart Newt":{"Cave Cricket":1.0},"Giant Cave Toad":{"Blind Newt":0.3,"Cave Cricket":0.2,"Diving Beetle":0.2,"Giant Water Bug":0.1,"Dragonfly Nymph":0.1,"Diver":0.1},
"Cave Crayfish":{"Cave Isopod":0.5,"Bristle Worm":0.5},"Fishing Spider":{"Blind Cavefish":0.5,"Blind Newt":0.5},"Cave Cricket":{"Cave moss":1.0},"Diving Beetle":{"Amphipod":1.0},
"Giant Water Bug":{"Blind Newt":0.6,"Blind Cavefish":0.4},"Dragonfly Nymph":{"Blind Cavefish":0.5,"Amphipod":0.5},"Glowworm Colony":{"Cave Cricket":0.6,"Plankton":0.4},
"Firefly Squid":{"Blind Cavefish":0.6,"Cave Krill":0.4},"Lanternfish":{"Cave Krill":1.0},"Cave Anglerfish":{"Blind Cavefish":0.5,"Firefly Squid":0.5},
"Cave Eel":{"Blind Cavefish":0.4,"Firefly Squid":0.3,"Cave Crayfish":0.3},"Electric Ray":{"Cave Crayfish":0.5,"Blind Cavefish":0.5},"Blind Catfish":{"Cave Crayfish":0.3,"Blind Cavefish":0.3,"Cave Isopod":0.2,"Corpse":0.2},
"Whip Ray":{"Troglobite Crab":0.5,"Glass Shrimp":0.5},"Hagfish":{"Corpse":1.0},"Vampire Squid":{"Detritus":0.7,"Corpse":0.3},"Bristle Worm":{"Corpse":0.5,"Chemosynthetic mat":0.5},
"Sea Spider":{"White anemone cluster":0.6,"Cave sponge":0.4},"Cave Swiftlet":{"Cave Cricket":0.7,"Fishing Spider":0.3},"Snapping Turtle":{"Blind Newt":0.4,"Blind Cavefish":0.3,"Stone lettuce":0.3},
"Cave Krait":{"Blind Newt":0.5,"Blind Cavefish":0.5},"Epaulette Shark":{"Troglobite Crab":0.4,"Cave Crayfish":0.3,"Bristle Worm":0.3},"Current Runner":{"Blind Cavefish":0.6,"Firefly Squid":0.4},
"Cave Sturgeon":{"Cave Krill":0.4,"Stone lettuce":0.3,"Chemosynthetic mat":0.3},"Gulper Eel":{"Lanternfish":0.5,"Firefly Squid":0.3,"Vampire Squid":0.2},
"Giant Salamander":{"Olm":0.3,"Cave Crayfish":0.3,"Blind Catfish":0.2,"Diver":0.2},"Cave Caiman":{"Giant Cave Toad":0.3,"Snapping Turtle":0.2,"Giant Salamander":0.2,"The Drowned":0.1,"Diver":0.2},
"Sleeper Shark":{"Cave Caiman":0.2,"Gulper Eel":0.2,"Cave Sturgeon":0.2,"Whip Ray":0.1,"Cave Anglerfish":0.1,"Corpse":0.2},"Ghost Worm":{"The Drowned":0.7,"Cave Eel":0.3},
"Silt Lamprey":{"Blind Catfish":0.4,"Cave Sturgeon":0.4,"Gulper Eel":0.2},"The Lobster":{"Cave Caiman":0.3,"Sleeper Shark":0.2,"The Drowned":0.2,"Diver":0.3},
}
FOODS=["Plankton","Detritus","Corpse","Parasites","Glow mould","Chemosynthetic mat","Cave moss","Stone lettuce","Cave sponge","White anemone cluster","The Drowned","Diver"]
FLORA=[("Glow mould","Luminous producer","Flooded Gallery, Chimney, Cathedral","Base of the wet web; lights corridors; brighter where cavefish are fewer",0,"Blind Cavefish",1.0,60),
("Chemosynthetic mat","Producer","The Sump, Dynamo Sump","Base of the sump web at the vents",0,"Cave Krill, Bristle Worm, Cave Sturgeon",1.0,45),
("Pale cave moss","Producer","Dry Chambers","Insect and newt food",0,"Cave Cricket, Amphipod, Blind Newt, Poison Dart Newt",0.8,90),
("Snottite curtain","Hazard","Chimney ledges, Squeeze","Acid drip: 5/s underneath",5,"",0,0),
("Crystal coral","Hazard/Tool","The Cathedral","Sharp (bleed on touch); shooting a cluster rings it: calls the Lobster and makes it Rear",6,"",0,0),
("Root tangle","Shelter","Flooded Gallery ceiling, Dry Chambers","Hides divers; crayfish and spiders nest here",0,"",0,0),
("Drip fungus","Hazard","Dry Chambers","Spore cloud when disturbed: slow 30% for 5 s",0,"",0,0),
("Ink cap","Tool","Flooded Gallery, Cathedral","Bursts into an 8 s ink cloud when shot",0,"",0,300),
("Bloodvine","Tool/Trap","Gallery, Dynamo Sump (near the Forge)","Cut or shot: smells like 40 blood for 30 s",0,"",0,240),
("Cave sponge","Shelter","Flooded Gallery","Glass shrimp and sponges' guests inside",0,"Sea Spider",0.3,120),
("White anemone cluster","Hazard","Gallery, Cathedral floor","Holds size 1; stings divers 8",8,"Sea Spider",0.3,120),
("Stone lettuce","Producer","The Sump, Dry Chambers pools","Sturgeon and snapping turtle food",0,"Cave Sturgeon, Snapping Turtle",0.5,120)]
# Layout: a ring. Coordinates in metres (x east, y south on the plan), depth in metres below the Mouth.
ZONES=[ # name, level, x, y, w, h, door_cost, depth_m, notes
("The Mouth","Wet",30,0,16,10,0,0,"Start pocket under a light shaft. Gannet rack, Juggernaut. Slipstream F arrives here."),
("The Flooded Gallery","Wet",0,14,40,16,750,-10,"Columns and root tangles; Needler Mk I, Quick Brine, workbench; the Ghost Worm's wall on the south side; slipstream A departs east"),
("The Chimney","Wet (vertical)",48,12,14,14,1000,"-10 to -40","A shaft with four ledges: Long Speargun (ledge 2); stalactites overhead (trap anchor at ledge 4); glowworms; slipstream B departs at the bottom"),
("The Squeeze","Wet (crawl)",8,32,8,10,0,-25,"A one-way crawl tunnel Gallery -> Sump; no weapons drawn; 40 s crawl; the Ghost Worm lives in its walls"),
("Dry Chamber I: the Cricket Cavern","Air",70,4,18,12,1250,-15,"Walking; cave moss, crickets, swiftlet roost; Speed Brine; the Drowned's camp and entry (the Lantern Cache)"),
("Dry Chamber II: the Toad Pool","Air",70,20,18,12,0,-15,"A pool with the toad, newts, kraits; Carbine rack; the salamander under the far ledge"),
("Dry Chamber III: the Roost","Air",90,12,14,14,0,-15,"A tall chamber; ledges; the caiman's haul-out; slipstream C departs from the pool at its floor"),
("The Sump","Wet",20,46,44,18,1500,-45,"Silt bottom; vents and mats; Bolt Harpoon, Double Shot; sleeper shark, electric rays; slipstream B and the Squeeze arrive; slipstream D departs"),
("The Dynamo Sump","Wet",70,44,22,16,1750,-40,"The drowned expedition's generator (power); the Pressure Forge; Bloodvine by the Forge; slipstreams C and D arrive; E departs"),
("The Cathedral","Wet",50,66,44,24,2000,-30,"Crystal coral; the Lobster's home; Kick Brine, Locker spot 2; two Cathedral overlooks onto the Sump; slipstream F departs back to the Mouth"),
]
LINKS=[("The Mouth","The Flooded Gallery",750,"The throat (a swim-down)"),("The Flooded Gallery","The Chimney",1000,"Chimney door"),
("The Flooded Gallery","The Squeeze",0,"Crawl entrance (one-way)"),("The Squeeze","The Sump",0,"Crawl exit (one-way)"),
("The Chimney","Dry Chamber I: the Cricket Cavern",1250,"Ledge 3 airlock (a natural sump you surface through)"),
("Dry Chamber I: the Cricket Cavern","Dry Chamber II: the Toad Pool",0,"Open passage"),("Dry Chamber II: the Toad Pool","Dry Chamber III: the Roost",0,"Open passage"),
("The Chimney","The Sump",1500,"Chimney bottom"),("The Sump","The Dynamo Sump",1750,"Generator door"),("The Dynamo Sump","The Cathedral",2000,"Crystal gate"),
("The Cathedral","The Sump",0,"Overlook drops (one-way, 2 places)")]
STREAMS=[ # id, from, to, length_m, ride_s, hazard
("A","The Flooded Gallery","The Chimney (top)",40,5,"Current Runner patrols"),
("B","The Chimney (bottom)","The Sump",50,6,"Ends in silt: electric rays"),
("C","Dry Chamber III: the Roost (pool)","The Dynamo Sump",60,8,"Passes the caiman's haul-out"),
("D","The Sump","The Dynamo Sump",30,4,"Fast and safe; the cave's highway"),
("E","The Dynamo Sump","The Cathedral",40,5,"Arrives under the crystal coral (touching it bleeds)"),
("F","The Cathedral","The Mouth",120,15,"The escape stream: long, dark, Current Runner and Cave Eels; loops the whole map")]
POI=[("Gannet rack","Rack","The Mouth",32,2),("Juggernaut Brine","Tonic","The Mouth",43,8),("Needler Mk I rack","Rack","The Flooded Gallery",4,16),("Quick Brine","Tonic","The Flooded Gallery",36,28),
("Workbench","Build","The Flooded Gallery",20,22),("Locker spot 1","Locker","The Flooded Gallery",30,16),("Ghost Worm wall","Boss","The Flooded Gallery",10,29),("Cleaner station (sponges)","Feature","The Flooded Gallery",14,18),
("Long Speargun rack (ledge 2)","Rack","The Chimney",50,20),("Stalactite trap anchor (ledge 4)","Trap","The Chimney",55,14),("Glowworm ceiling","Feature","The Chimney",58,24),
("Speed Brine","Tonic","Dry Chamber I: the Cricket Cavern",72,6),("The Lantern Cache (Drowned entry)","Entry","Dry Chamber I: the Cricket Cavern",86,14),("Swiftlet roost","Hazard","Dry Chamber I: the Cricket Cavern",80,6),
("Sea-Pattern Carbine rack","Rack","Dry Chamber II: the Toad Pool",72,22),("Toad pool","Hazard","Dry Chamber II: the Toad Pool",80,26),("Salamander ledge","Hazard","Dry Chamber II: the Toad Pool",86,30),
("Caiman haul-out","Hazard","Dry Chamber III: the Roost",96,14),("Slipstream C mouth","Feature","Dry Chamber III: the Roost",97,24),
("Bolt Harpoon rack","Rack","The Sump",24,48),("Double Shot","Tonic","The Sump",60,62),("Vent field & mats","Feature","The Sump",44,56),("Sleeper shark silt","Hazard","The Sump",30,60),("Electric ray silt","Hazard","The Sump",52,50),
("Power switch (generator)","Power","The Dynamo Sump",74,46),("Pressure Forge","Forge","The Dynamo Sump",86,56),("Bloodvine by the Forge","Hazard","The Dynamo Sump",82,58),("Expedition wreckage (parts)","Build","The Dynamo Sump",78,52),
("Kick Brine","Tonic","The Cathedral",54,86),("Locker spot 2","Locker","The Cathedral",90,86),("Crystal coral (calls the Lobster)","Feature","The Cathedral",72,78),("The Lobster's hollow","Boss","The Cathedral",84,72),("Overlook drops to the Sump","Feature","The Cathedral",52,68),("Slipstream F mouth","Feature","The Cathedral",92,68)]
SPAWN=[("The Mouth","Blind Cavefish",20,20),("The Mouth","Glass Shrimp",4,300),
("The Flooded Gallery","Blind Cavefish",60,20),("The Flooded Gallery","Glass Shrimp",8,300),("The Flooded Gallery","Troglobite Crab",6,120),("The Flooded Gallery","Cave Crayfish",6,180),("The Flooded Gallery","Cave Eel",3,300),("The Flooded Gallery","Whip Ray",1,400),("The Flooded Gallery","Sea Spider",3,240),
("The Squeeze","Ghost Worm",1,0),
("The Chimney","Glowworm Colony",1,0),("The Chimney","Firefly Squid",12,120),("The Chimney","Blind Cavefish",30,20),("The Chimney","Cave Eel",2,300),
("Dry Chamber I: the Cricket Cavern","Cave Cricket",1,60),("Dry Chamber I: the Cricket Cavern","Amphipod",20,60),("Dry Chamber I: the Cricket Cavern","Blind Newt",6,120),("Dry Chamber I: the Cricket Cavern","Poison Dart Newt",4,180),("Dry Chamber I: the Cricket Cavern","Fishing Spider",2,240),("Dry Chamber I: the Cricket Cavern","Cave Swiftlet",20,120),("Dry Chamber I: the Cricket Cavern","Diving Beetle",8,90),
("Dry Chamber II: the Toad Pool","Giant Cave Toad",1,400),("Dry Chamber II: the Toad Pool","Blind Newt",6,120),("Dry Chamber II: the Toad Pool","Cave Krait",2,300),("Dry Chamber II: the Toad Pool","Giant Water Bug",3,180),("Dry Chamber II: the Toad Pool","Dragonfly Nymph",3,180),("Dry Chamber II: the Toad Pool","Giant Salamander",1,600),("Dry Chamber II: the Toad Pool","Snapping Turtle",1,500),("Dry Chamber II: the Toad Pool","Olm",3,240),
("Dry Chamber III: the Roost","Cave Caiman",1,700),("Dry Chamber III: the Roost","Epaulette Shark",2,300),("Dry Chamber III: the Roost","Cave Swiftlet",20,120),("Dry Chamber III: the Roost","Olm",2,240),
("The Sump","Cave Krill",1,60),("The Sump","Cave Isopod",10,90),("The Sump","Lanternfish",25,30),("The Sump","Cave Anglerfish",2,400),("The Sump","Electric Ray",3,400),("The Sump","Blind Catfish",3,300),("The Sump","Hagfish",3,240),("The Sump","Vampire Squid",3,240),("The Sump","Bristle Worm",5,180),("The Sump","Cave Sturgeon",1,600),("The Sump","Gulper Eel",2,500),("The Sump","Sleeper Shark",1,900),("The Sump","Silt Lamprey",4,120),
("The Dynamo Sump","Blind Cavefish",30,20),("The Dynamo Sump","Cave Eel",2,300),("The Dynamo Sump","Blind Catfish",1,300),
("The Cathedral","The Lobster",1,0),("The Cathedral","Firefly Squid",10,120),("The Cathedral","Sea Spider",4,240),("The Cathedral","Cave Eel",2,300),
("Slipstreams","Current Runner",3,400)]
BOSS=["The Lobster — Depth's Cave mini-boss grown to a boiler-sized cave lobster; arena = the Cathedral until tide 12, then any hall it can reach by slipstream (it rides E and F).",
"HP 15,000 (x1.08 per tide); front shell halves damage; weak point: the underside, exposed 3 s when it Rears. It Rears when the crystal coral rings (a shot cluster) or after taking 800 damage in 5 s.",
"Phase 1 (100-60%): Crush (claw grab: destroys a Shell Shield, holds 2 s), Sweep (knockback), Clack (stun 1 s in 10 m, 10 noise). Patrols the Cathedral floor; ignores divers on the overlooks.",
"Phase 2 (60-30%): moves onto the walls and ceiling (upside-down, hard to hit); Clack now drops one stalactite per use on a marked square; summons 4 Troglobite Crabs from the crystal.",
"Phase 3 (30-0%): rides slipstream E backward into the Dynamo Sump and cuts the power (the Forge and traps go dark until the switch is reset); its Clack drops 3 stalactites; Rear only from coral rings.",
"Arena rules: ringing the coral costs a shot and 6 noise but forces a Rear; the overlook drops let divers reset by falling to the Sump (the Lobster follows by slipstream in 20 s); ink caps in the Cathedral blind it 5 s.",
"Kill reward: 1,500 base scrip x tide, a Locker weapon each, and the expedition's key (opens the Lantern Cache's locked crate: a free wonder weapon). Reforms in the Cathedral after 6 minutes at 50% HP."]
FACTION=dict(name="The Drowned",intro="Ghost sailors from the lost expedition. They do not bleed, so no predator hunts them by scent; only the Ghost Worm and the Cave Caiman attack them (cold things). They never use slipstreams and walk the dry chambers as easily as they swim.",
units=[("Deckhand",140,"Boarding axe","30 melee, 1.0 s","Slow (1.2 swim, 1.0 walk)","Advances in a line; never retreats","Its lantern-less face glows faintly 1 s before it swings","220 scrip"),
("Lantern Bearer",120,"Lantern on a pole","0","Diver speed","Walks ahead of the squad; its light draws luminous-curious beasts (firefly squid, anglerfish) onto whoever stands near it; 30 nerves","The lantern flares before beasts arrive","Lantern (a 60 s flare item), 250"),
("Rope Hand",130,"Grapple line","15, then a 3 s drag","Diver speed","Hooks a diver and drags them toward the Deckhands","Coils the rope twice","260"),
("Bell Ringer",160,"Ship's bell","0","Slow","Rings: every beast in 30 m investigates the ringer's target (it points at a diver); 8 noise","Raises the bell overhead","Bell (a build part), 300"),
("The Bosun (Hunts)",900,"Cutlass and pistol","60 melee; 40 ranged","Diver speed; passes through stalagmites","Commands from the rear; Deckhands within 10 m ignore stun and slow","His lantern turns green before an order","Cutlass (melee), 600")],
tactics=["A squad enters at the Lantern Cache in the Cricket Cavern and walks Cavern -> Toad Pool -> Roost, then swims down the Chimney to the Gallery; it never enters a slipstream and never crawls the Squeeze.",
"On contact: the Lantern Bearer stands still (a lure), the Rope Hand hooks the nearest diver, the Deckhands close in a line, the Bell Ringer rings at the diver who is reviving or reloading.",
"They ignore beasts entirely; beasts ignore them except the Ghost Worm and the caiman. A squad walked past the Ghost Worm's wall loses two Deckhands.",
"They cannot be lured by chum or blinded by ink; flares confuse them (they walk toward flares). Nets hold them 4 s. Melee kills them fastest (axes are silent and they are slow).",
"In a Hunt the Bosun waits in the Roost; the squads try to drive the divers up into the dry chambers where they walk faster than divers."],
barks=["Spotting: 'Living ones. Fetch the lanterns.' / 'Down here we're all crew.'","Bell: 'Ring them in.' / 'The bell calls what's hungry.'","Ghost Worm attacks them: 'It knows us. Back, back!'","A Deckhand falls: 'He'll be back at the cache.' / 'Ninety days out and no relief.'","Rope Hand: 'Line fast. Haul.'","Bosun: 'Every hand to the light. Bring them below.' / 'The captain wants a full muster.'"])
NOTES=["Training loop (wet): Gallery -> slipstream A -> Chimney -> Chimney bottom -> Sump -> slipstream D -> Dynamo -> slipstream E -> Cathedral -> slipstream F -> Mouth -> Gallery. About 3 minutes; every stream has a beast in it.",
"Training loop (dry): Cavern -> Toad Pool -> Roost -> Cavern, on foot; safe from everything wet, unsafe from the toad, the salamander, and the caiman; where the Drowned are strongest.",
"Blood flow: slipstreams carry blood the way they carry divers, so a kill in the Gallery smells in the Chimney 5 s later and in the Sump 11 s later; the Sump is the map's drain (blood pools there and calls the sleeper shark).",
"Sightlines: Gallery 20 m between columns; Chimney vertical 30 m; dry chambers 15 m; Sump 6-10 m in silt; Cathedral 40 m across (the long-gun room). Alarm: one region; the Drowned enter from the Lantern Cache.",
"Rockfall: any noise-6+ shot in the Chimney or Cathedral has a 5% chance to drop a stalactite (200 damage) within 8 m of the shooter's target."]
